### ISSUE TITLE
Publisher occasionally fails due to being unable to determine sha1 of commit

### ISSUE THREAD

**Issue by ixdy** [jenkinsci/ghprb-plugin#104]
I've occasionally seen the publisher fail test runs because it supposedly can't determine the sha1 of the commit, and yet on the very next line, it shows it successfully updating the relevant commit.

This doesn't always occur, but I haven't been able to figure out what triggers this bug. In this particular case, I had just turned on the "Execute concurrent builds if necessary" option in Jenkins, but it'd successfully checked out the patch, built and run all of the tests up to the point of publishing results.

Build log from one of the failures:
```
GitHub pull request #9592 of commit 9423f80d2011d2d5ef2e5e121f0e97f0d499bfb1, no merge conflicts.
Setting status of 9423f80d2011d2d5ef2e5e121f0e97f0d499bfb1 to PENDING with url [elided] and message: 'Build started, sha1 is merged'
Using conext: Jenkins GCE e2e
Building in workspace /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/GoogleCloudPlatform/kubernetes # timeout=10
Fetching upstream changes from https://github.com/GoogleCloudPlatform/kubernetes
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/GoogleCloudPlatform/kubernetes +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/9592/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/9592/merge^{commit} # timeout=10
Checking out Revision 0af5cfe1266faebf8f0162a0efce08b590c0337c (refs/remotes/origin/pr/9592/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 0af5cfe1266faebf8f0162a0efce08b590c0337c
First time build. Skipping changelog.
```
...
```
ERROR: Publisher 'Set build status on GitHub commit' aborted due to exception: 
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
	at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Setting status of 9423f80d2011d2d5ef2e5e121f0e97f0d499bfb1 to FAILURE with url [elided] and message: 'Build finished.'
Using conext: Jenkins GCE e2e
GCE e2e build/test **failed** for commit 9423f80d2011d2d5ef2e5e121f0e97f0d499bfb1.
...
```

**Comment by lfilho** [comment]
Also happening to me. Jenkins 1.618 + GHPRB 1.26.2

**Comment by DavidTanner** [comment]
So this is the GitHubCommitNotifier plugin that is trying to run.  You want to remove that post build step as the GitHub Pull Request Builder plugin handles updating the status.  

The issue happens because the Notifier plugin is trying to resolve the merged commit, not the real one.  Note in the checkout it uses commit ```0af5cfe1266faebf8f0162a0efce08b590c0337c```, so once any post build steps complete that update the branch ```0af5cfe1266faebf8f0162a0efce08b590c0337c``` is no more.  The real commit is ```9423f80d2011d2d5ef2e5e121f0e97f0d499bfb1```

**Comment by lfilho** [comment]
That was indeed it! I removed the pre and post build steps for updating the commit status and it worked! Thanks!

**Comment by stefanhoth** [comment]
came here to say thanks because we ran into the same issue today. :+1:

**Comment by mehtadev17** [comment]
:+1:

**Comment by brainsik** [comment]
:bow:

**Comment by guruvamsichintala** [comment]
It worked
