### ISSUE TITLE
NPE with 1.24 version

### ISSUE THREAD

**Issue by clstokes** [jenkinsci/ghprb-plugin#116]
We're getting a NullPointerException with version 1.24 of this plugin. This happens after the build completes and the pull request on GitHub is left in a *pending* state.

This is with Jenkins ver. 1.616 (and ver. 1.617) and version 1.24 of ghprb. Manually downgrading to 1.23 resolves this issue.

![image](https://cloud.githubusercontent.com/assets/293763/8264179/ffd299a4-1697-11e5-8fd7-3b35f3af1e2f.png)

```
Job #15 main build action completed: FAILURE
Jun 19, 2015 9:53:50 PM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:134)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
```

**Comment by DavidTanner** [comment]
I had reversed logic.  Will be out in 1.24.1

**Comment by clstokes** [comment]
Any estimate for when 1.24.1 will be released?

**Comment by DavidTanner** [comment]
Three days ago, just do a refresh in update-center

**Comment by clstokes** [comment]
Oh, thanks! :100:
