### ISSUE TITLE
Credential issues still continue after #123

### ISSUE THREAD

**Issue by arcivanov** [jenkinsci/ghprb-plugin#124]
The credentials issue is not fully resolved in #123 

Comments are not left by GHPRB in the PRs being tested even though the appropriate global configuration is set. The GitHub status API updates complete successfully though.

```
Jun 29, 2015 4:30:29 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: issue_comment
Jun 29, 2015 4:30:29 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context (null)
Jun 29, 2015 4:30:29 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking issue comment 'org.kohsuke.github.GHIssueComment@5dcd4aef' for repo cschcs/kesem
Jun 29, 2015 4:30:29 PM FINER org.jenkinsci.plugins.ghprb.GhprbRepository
Comment on issue #2 from User:arcivanov: test this please
Jun 29, 2015 4:30:29 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Retest phrase
Jun 29, 2015 4:30:29 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Admin User:arcivanov gave retest phrase
Jun 29, 2015 4:30:30 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jun 29, 2015 4:30:30 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jun 29, 2015 4:30:30 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
Jun 29, 2015 4:30:30 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: issue_comment
Jun 29, 2015 4:30:30 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context (null)
Jun 29, 2015 4:30:31 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getBuilder
Failed to look up credentials for context (null) using id: 2c6f0a56-02f2-4082-88ca-143fa817b765
Jun 29, 2015 4:30:31 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: issue_comment
Jun 29, 2015 4:30:31 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context (null)
Jun 29, 2015 4:31:00 PM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger
Use webHooks is set, so not running trigger
```

**Comment by DavidTanner** [comment]
Would you be able to run a rogue build?  I have a thought for where it might be failing in the lookup.

**Comment by arcivanov** [comment]
Totally!

**Comment by DavidTanner** [comment]
If you would please get the same log.  The context shouldn't be (null).

**Comment by arcivanov** [comment]
Will do. Please standby.

**Comment by arcivanov** [comment]
The null context is gone. This appeared:


Jul 02, 2015 2:37:44 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getBuilder

Failed to look up credentials for context Koji Job Generator (PR) using id: 2c6f0a56-02f2-4082-88ca-143fa817b765


This wasn't there before and this job is definitely accessible (verified with Github web access for those credentials).

**Comment by arcivanov** [comment]
Still no comments on the PR being built.

From: Arcadiy Ivanov <arcadiy@csc.com<mailto:arcadiy@csc.com>>
Date: Wednesday, July 1, 2015 at 22:41
To: jenkinsci/ghprb-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>, jenkinsci/ghprb-plugin <ghprb-plugin@noreply.github.com<mailto:ghprb-plugin@noreply.github.com>>
Subject: Re: [ghprb-plugin] Credential issues still continue after #123 (#124)


The null context is gone. This appeared:


Jul 02, 2015 2:37:44 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getBuilder

Failed to look up credentials for context Koji Job Generator (PR) using id: 2c6f0a56-02f2-4082-88ca-143fa817b765


This wasn't there before and this job is definitely accessible (verified with Github web access for those credentials).

**Comment by DavidTanner** [comment]
If you try testing it again from the main configuration page, does it connect successfully?

**Comment by arcivanov** [comment]
From main config page all appears to be in order:

```
Test Credentials	
Connect to API
Connected to https://api.github.com as
Repository owner/name		
ServiceMesh/koji-jenkins-dsl
Check repo permissions
User has access to: Push, Pull

Test Credentials	
Connect to API
Connected to https://api.github.com as
Repository owner/name		
cschcs/kesem
Check repo permissions
User has access to: Admin, Push, Pull
```

Found this in startup logs though:

```
Jul 02, 2015 2:33:25 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
Could not retrieve GitHub repository named ServiceMesh/koji-jenkins-dsl (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:321)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:78)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.Ghprb.init(Ghprb.java:105)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:170)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:51)
	at hudson.model.AbstractProject.onLoad(AbstractProject.java:326)
	at hudson.model.Project.onLoad(Project.java:98)
	at hudson.model.Items.load(Items.java:320)
	at jenkins.model.Jenkins$17.run(Jenkins.java:2651)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:904)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/ServiceMesh/koji-jenkins-dsl
	at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 19 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/ServiceMesh/koji-jenkins-dsl
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 20 more
```

**Comment by arcivanov** [comment]
Maybe cranking up logging on commenting would help?

**Comment by DavidTanner** [comment]
What does the domain information for the credentials look like?  Does it have the correct scheme, host, port, and path?

**Comment by arcivanov** [comment]
It's "Global credentials (unrestricted)", "secret text" with no domain information whatsoever. This is how new credential is registered when added from the main settings page.

**Comment by DavidTanner** [comment]
I can't get my setup to do it.

**Comment by arcivanov** [comment]
Jenkins 1.609.1 ?

**Comment by arcivanov** [comment]
Security enabled. Security via OAuth to GitHub

**Comment by DavidTanner** [comment]
the the logger, do you see the context text still?

**Comment by arcivanov** [comment]
Nope, I don't see the context (null) anymore, but I see this:

```
Jul 02, 2015 2:37:44 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getBuilder
Failed to look up credentials for context Koji Job Generator (PR) using id: 2c6f0a56-02f2-4082-88ca-143fa817b765
```

and on cschcs/kesem the comments are not posted in the PR request even though main settings specify those to be posted.

**Comment by DavidTanner** [comment]
I wonder if the plugin should just forget about context?  Just use the jenkins instance.

**Comment by arcivanov** [comment]
If the credential is specified as Global there should not be any context used I would think.

**Comment by arcivanov** [comment]
Also could you add comments logging ad-nauseam, cause no comments are posted at all.

**Comment by arcivanov** [comment]
```
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context HCS - Kesem - (PR) - (Autogen)
Jul 02, 2015 3:56:46 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking issue comment 'org.kohsuke.github.GHIssueComment@27f1ba1d' for repo cschcs/kesem
Jul 02, 2015 3:56:46 AM FINER org.jenkinsci.plugins.ghprb.GhprbRepository
Comment on issue #2 from User:arcivanov: test this please
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Retest phrase
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Admin User:arcivanov gave retest phrase
Jul 02, 2015 3:56:46 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #2 was updated on cschcs/kesem at 7/2/15 3:56 AM by User:arcivanov
Jul 02, 2015 3:56:46 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #2 was updated on repo cschcs/kesem but there aren't any new comments nor commits; that may mean that commit status was updated.
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jul 02, 2015 3:56:46 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
```

**Comment by DavidTanner** [comment]
I just sent you another build with some more logging.

**Comment by arcivanov** [comment]
trying it already

**Comment by arcivanov** [comment]
seems like something didn't resolve in messages: "Looking up credentials for {0}, using context {1} for url {2}"

**Comment by DavidTanner** [comment]
single quotes I guess tell it not to replace the number.  Redo

**Comment by DavidTanner** [comment]
It should look like this
Jul 02, 2015 12:20:11 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for d9535634-c7b0-46dc-b2dc-c57576ad9744, using context Testing for url https://api.github.com
Jul 02, 2015 12:20:21 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 1 credentials
Jul 02, 2015 12:20:21 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Testing

**Comment by arcivanov** [comment]
Ah, so one nailed down:

```
Jul 02, 2015 4:25:48 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getBuilder
Failed to look up credentials for context Koji Job Generator (PR) using id: 2c6f0a56-02f2-4082-88ca-143fa817b765
Jul 02, 2015 4:25:48 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
Could not retrieve GitHub repository named ServiceMesh/koji-jenkins-dsl (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
...
Stopping the ghprb trigger for project Koji Job Generator (PR)
Jul 02, 2015 4:44:40 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger start
Starting the ghprb trigger for the Koji Job Generator (PR) job; newInstance is true
Jul 02, 2015 4:44:40 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 2d50728a-b29c-4b16-814b-0d6723e70beb, using context Koji Job Generator (PR) for url https://api.github.com
Jul 02, 2015 4:44:40 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Jul 02, 2015 4:44:40 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Koji Job Generator (PR)
Jul 02, 2015 4:44:40 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository createHook
Couldn't create web hook for repository ServiceMesh/koji-jenkins-dsl. Does the user (from global configuration) have admin rights to the repository?
```

Somehow "Koji Job Generator (PR)" had a credential UUID that was not default: 2c6f0a56-02f2-4082-88ca-143fa817b765 vs 2d50728a-b29c-4b16-814b-0d6723e70beb

Still no comments in PR being built:

```
Got payload event: issue_comment
Jul 02, 2015 4:49:43 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 2d50728a-b29c-4b16-814b-0d6723e70beb, using context HCS_-_Kesem_-_(PR)_-_(Autogen) for url https://api.github.com
Jul 02, 2015 4:49:43 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context HCS - Kesem - (PR) - (Autogen)
Jul 02, 2015 4:49:43 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking issue comment 'org.kohsuke.github.GHIssueComment@569e1b84' for repo cschcs/kesem
Jul 02, 2015 4:49:43 AM FINER org.jenkinsci.plugins.ghprb.GhprbRepository
Comment on issue #2 from User:arcivanov: test this please
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Retest phrase
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Admin User:arcivanov gave retest phrase
Jul 02, 2015 4:49:43 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #2 was updated on cschcs/kesem at 7/2/15 4:49 AM by User:arcivanov
Jul 02, 2015 4:49:43 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #2 was updated on repo cschcs/kesem but there aren't any new comments nor commits; that may mean that commit status was updated.
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jul 02, 2015 4:49:43 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
```

**Comment by arcivanov** [comment]
I have tried 1.24.5.

I have "Use comments to report intermediate phases: triggered et al" checked in Jenkins global config. No error messages appear in the Jenkins logs or in the build logs. *No comments in the PR either*.

**Comment by DavidTanner** [comment]
So that setting is a little deceiving, it only is called if the status update fails. It is shown easiest using version an earlier version.  
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.20.1/src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java#L166

In the later versions if the status updates fail, then the comment logic is called
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.24.5/src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.24.5/src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java#L170

**Comment by arcivanov** [comment]
What about default uncustomized build-success/build-failure comments? Same?

**Comment by DavidTanner** [comment]
The build messages were always configured per job, with a global default when creating a new job.  The values that were there before should have been kept accross the update.

**Comment by arcivanov** [comment]
Should the default SUCCESS/FAIL comments be posted by default like in 1.23? I can't get GHPRB to comment on anything.

**Comment by DavidTanner** [comment]
There is only a default if you add it.

**Comment by DavidTanner** [comment]
I have the latest running on my own branch, and I do get the comments that I add for SUCCESS/FAIL.
https://github.com/DavidTanner/Testing/pull/12

**Comment by DavidTanner** [comment]
Sorry, I didn't understand your message.  The default shouldn't be posted unless it is also on the job.  There have been several issues opened about not having anything posted to the comments.  The default appears if you select the option on the build.

**Comment by DavidTanner** [comment]
by build I mean the job configuration.

**Comment by arcivanov** [comment]
I see. So that is a behavioral change from pre-1.24? Because there used to be default build success/failure comments and this change basically breaks automation that configures GHPRB.

There used to be defaults for Success and Failure comments with failures including last N lines of stdout logs. Now there is nothing apparently unless I configure.

Is there a reference for what variables expand in the messages?

**Comment by DavidTanner** [comment]
Any environment variables available when the step runs will be expanded in the build message.  I can see adding a setting that will tell the plugin to use global values if local settings aren't present.

So yes, this does change default behavior.

**Comment by arcivanov** [comment]
Is there any way to dump build console output lines in the comment?

**Comment by DavidTanner** [comment]
That is what the log lines except extension is for

**Comment by arcivanov** [comment]
Sorry, extension?

**Comment by DavidTanner** [comment]
The extensions are in the drop down list at the end of the configuration section.  Things like build messages, log lines, commit status, etc.
