### ISSUE TITLE
RunListener failed - Build Passes do not update commit statuses

### ISSUE THREAD

**Issue by techman83** [jenkinsci/ghprb-plugin#133]
I've had a good poke around at the config, but whilst the plugin is able to set the status of a build/commit to in progress or failure - successes cause the following:

```
Jul 08, 2015 9:05:20 AM hudson.model.Run execute
INFO: NetKAN #43 main build action completed: SUCCESS
Jul 08, 2015 9:05:20 AM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NoClassDefFoundError: hudson/tasks/test/TestObject
	at org.jenkinsci.plugins.ghprb.manager.factory.GhprbBuildManagerFactoryUtil.getBuildManager(GhprbBuildManagerFactoryUtil.java:37)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:155)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.test.TestObject
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
```

Jenkins: 1.619
GHPRB: 124.7

The actual problem we're seeing is the commit status not updating here:
https://github.com/KSP-CKAN/NetKAN/pull/1869

However it has improved from 124.6 which was not updating the build at all for a pass (at least now it gives a green tick for the overall build).

Failures do update the commit status.  Is there some way I can export the job config, because I'm not 100% confident what a correctly configured job looks like (Maintainer of old Jenkins host is MIA and the host went AWAL - so we're starting from scratch).

Thanks!

**Comment by DavidTanner** [comment]
This is an issue with JUnit.  See https://github.com/janinko/ghprb/issues/290

**Comment by techman83** [comment]
Ok that's awesome! Thanks working properly now.
