### ISSUE TITLE
1.28 fails with NPEs

### ISSUE THREAD

**Issue by arcivanov** [jenkinsci/ghprb-plugin#184]
```
Sep 22, 2015 10:15:29 PM SEVERE org.jenkinsci.plugins.ghprb.Ghprb getEnvVars
Couldn't get Env Variables: 
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: ghprbAuthorRepoGitUrl
	at hudson.EnvVars.put(EnvVars.java:356)
	at hudson.model.StringParameterValue.buildEnvironment(StringParameterValue.java:56)
	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:944)
	at org.jenkinsci.plugins.ghprb.Ghprb.getEnvVars(Ghprb.java:276)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:183)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:178)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:172)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by arcivanov** [comment]
And after fixing that - this:
```
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:193)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onEnvironmentSetup(GhprbSimpleStatus.java:127)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onEnvironmentSetup(GhprbBuilds.java:223)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.setUpEnvironment(GhprbBuildListener.java:40)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:574)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:494)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by jlebon** [comment]
Noticed this as well. I'm working on a PR to fix those.

**Comment by arcivanov** [comment]
I'm already testing the fixes
