### ISSUE TITLE
Anonymous PR object causing failed merge on the private repo

### ISSUE THREAD

**Issue by arcivanov** [jenkinsci/ghprb-plugin#199]
```
2015-09-25 23:24:32.216: null (null)  has commits in PR[45999990] that is to be merged
2015-09-25 23:24:32.216: Merging the pull request
2015-09-25 23:24:32.236: ERROR: Publisher 'Github Pull Request Merger' aborted due to exception: 
2015-09-25 23:24:32.236: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button"}
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester.handleApiError(Requester.java:501)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester._to(Requester.java:248)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester.to(Requester.java:194)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester.to(Requester.java:182)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.GHPullRequest.merge(GHPullRequest.java:283)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.GHPullRequest.merge(GHPullRequest.java:269)
2015-09-25 23:24:32.236: 	at org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge.perform(GhprbPullRequestMerge.java:186)
2015-09-25 23:24:32.236: 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
2015-09-25 23:24:32.236: 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
2015-09-25 23:24:32.236: 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
2015-09-25 23:24:32.236: 	at hudson.model.Build$BuildExecution.post2(Build.java:183)
2015-09-25 23:24:32.236: 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
2015-09-25 23:24:32.236: 	at hudson.model.Run.execute(Run.java:1763)
2015-09-25 23:24:32.236: 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
2015-09-25 23:24:32.236: 	at hudson.model.ResourceController.execute(ResourceController.java:98)
2015-09-25 23:24:32.236: 	at hudson.model.Executor.run(Executor.java:381)
2015-09-25 23:24:32.236: Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cschcs/pyenv/pulls/24/merge
2015-09-25 23:24:32.236: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-09-25 23:24:32.236: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2015-09-25 23:24:32.236: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-09-25 23:24:32.236: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
2015-09-25 23:24:32.236: 	at java.security.AccessController.doPrivileged(Native Method)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester.parse(Requester.java:458)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester._to(Requester.java:227)
2015-09-25 23:24:32.236: 	... 14 more
2015-09-25 23:24:32.236: Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cschcs/pyenv/pulls/24/merge
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
2015-09-25 23:24:32.236: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
2015-09-25 23:24:32.236: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
2015-09-25 23:24:32.236: 	at org.kohsuke.github.Requester.parse(Requester.java:454)
2015-09-25 23:24:32.236: 	... 15 more
2015-09-25 23:24:32.239: Started calculate disk usage of build
2015-09-25 23:24:32.240: Finished Calculation of disk usage of build in 0 seconds
2015-09-25 23:24:32.282: Started calculate disk usage of workspace
2015-09-25 23:24:33.047: Finished Calculation of disk usage of workspace in 0 seconds
```

Happened two times in a row. Troubling signs are `null (null)` and `PR[45999990]` - where did number 45999990 come from?

**Comment by arcivanov** [comment]
related to #198?
