### ISSUE TITLE
Plugin triggering GitHub Rate Limits

### ISSUE THREAD

**Issue by JBodkin** [jenkinsci/ghprb-plugin#204]
Exception:

```
Sep 29, 2015 1:19:26 PM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: Error while accessing rate limit API
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/rate_limit
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.kohsuke.github.Requester.parse(Requester.java:458)
        at org.kohsuke.github.Requester._to(Requester.java:227)
        at org.kohsuke.github.Requester.to(Requester.java:194)
        at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:245)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:71)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:47)
        at org.jenkinsci.plugins.ghprb.Ghprb.init(Ghprb.java:86)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:205)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:52)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:331)
        at hudson.model.Project.onLoad(Project.java:98)
        at hudson.model.Items.load(Items.java:327)
        at hudson.model.ItemGroupMixIn.loadChildren(ItemGroupMixIn.java:109)
        at com.cloudbees.hudson.plugins.folder.Folder.onLoad(Folder.java:240)
        at hudson.model.Items.load(Items.java:327)
        at jenkins.model.Jenkins$17.run(Jenkins.java:2685)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:899)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/rate_limit
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.kohsuke.github.Requester.parse(Requester.java:454)
        ... 23 more
```

**Comment by arcivanov** [comment]
Hi thanks for the report. What is your plugin version?

**Comment by JBodkin** [comment]
Plugin Version: 1.29
Jenkins Version: 1.631

**Comment by JBodkin** [comment]
The exception occurred during Jenkins start-up, it seems it prevent Jenkins from correctly finishing the start-up procedures so therefore it appeared to have hung. I had to disable the job in order to start Jenkins

**Comment by arcivanov** [comment]
I presume you have an ungodly amount of GHPRB usage history, right?

**Comment by arcivanov** [comment]
Are you running GHPRB anonymously or in an authenticated fashion?

**Comment by DavidTanner** [comment]
@arcivanov do you know the reason for why the init code is calling getRateLimit, and can we remove it?

**Comment by arcivanov** [comment]
```java
            if (gitHub.getRateLimit().remaining == 0) {
                return false;
            }
```
Why? Beats me, probably there was a good reason in the past, but right now it's completely useless: the `false` returned by  `initGhRepository` is only checked in `check` of `GhprbRepository`, but `check`'s returned value is not checked anywhere so we can easily remove this.

**Comment by JBodkin** [comment]
Afraid first time user!

I've found the reason for the problem, it appears I misconfigured the secret key. After fixing that and waiting for the next period of rate limiting it works as expected.

Although I solved my problem, ideally the plugin would stop sending API requests when either the rate limit or unauthorised status code is received with the appropriate log messaging.

**Comment by DavidTanner** [comment]
@JBodkin That would make sense, but the only time the rate limit is checked is when initializing the repo.

**Comment by JBodkin** [comment]
It appears there are two scenarios whereby the error occurs, during startup and switch a build state from disabled to enabled.

**Comment by DavidTanner** [comment]
If the project is disabled, we probably shouldn't run the init code then.

**Comment by mmitche** [comment]
Once the fixes for the github-api go in, combined with various fixes made in the ghprb itself, this should no longer happen.

**Comment by v1v** [comment]
These are the related issues with the github-api and rate_limit:
- https://github.com/kohsuke/github-api/issues/273
Although it seems it was fixed in:
- https://github.com/kohsuke/github-api/issues/78


But i still get the same issues

**Comment by mmitche** [comment]
This is the critical PR for this: https://github.com/kohsuke/github-api/pull/283

Without that, User info requests can cause huge numbers of simultaneous API calls.

**Comment by bjoernhaeuser** [comment]
We are running the plugin in a very large setup and not hitting the limits, also the mentioned PRs are now already included. 

I therefore close the issue.
