### ISSUE TITLE
NPE on some project's PR that don't get auto-builded from triggers

### ISSUE THREAD

**Issue by vgallissot** [jenkinsci/ghprb-plugin#274]
Hi there,

For an unknown reason, a project didn't get build after first commit on a new branch after a Jenkins Update + plugin Update.
Then, "test this please" comment in PR cannot trigger a new build cause there's a NullPointerException because I guess there is no "last build"

````
Feb 24, 2016 5:24:04 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #1,522 was updated on $MyRepo at 2/24/16 5:23 PM by User:$SomeDev
Feb 24, 2016 5:24:04 PM hudson.triggers.Trigger checkTriggers
WARNING: org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@33271a82[$MyJobJenkins]
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.startJob(GhprbTrigger.java:298)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:78)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:325)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:318)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:161)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:174)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:154)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:281)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
````

A new commit in the PR has same issue cause imho there is still no "last build".
I guess I should force it or maybe adding entries anywhere to fake that "last build" ?

This project is well configured for more 1y now and all other PR are working fine, job is well configured and GitHub credentials etc. are correct.
I don't know how to bypass this error.

Thanks for any help anybody can provide !

Some Infos : 
 - Jenkins 1.649
 - ghprb 1.30.4

**Comment by vgallissot** [comment]
Why closed ?
We still have the problem with several projects and it's really frustrating !

We only can get rid of it by creating another git branch, git cherry-pick every commits from branchA to B and create another PR. It's quite a lost of time.

Can you tell me @DavidTanner what's wrong with my issue ?

**Comment by DavidTanner** [comment]
Please check with the latest version.  Nothing is wrong with the issue.

**Comment by vgallissot** [comment]
Thanks @DavidTanner I just updated from 1.30.4 to 1.30.6 and the problem is fixed.
I'm now able to rebuild any project even those who were generating NPE errors.

Thanks a lot,
Closing.
