### ISSUE TITLE
NPE with "Cancel build on update"

### ISSUE THREAD

**Issue by ixdy** [jenkinsci/ghprb-plugin#290]
I tried enabling the "Cancel build on update" option, but it resulted in most requests failing to run (though some did), and I see lots of NPEs in the Jenkins log like

```
WARNING: org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@7c2c4fa2[kubernetes
-pull-test-unit-integration]
java.lang.NullPointerException
        at org.jenkinsci.plugins.ghprb.extensions.build.GhprbCancelBuildsOnUpdate.cancelCurrentBuilds(GhprbCancelBui
ldsOnUpdate.java:44)
        at org.jenkinsci.plugins.ghprb.extensions.build.GhprbCancelBuildsOnUpdate.onScheduleBuild(GhprbCancelBuildsO
nUpdate.java:97)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.scheduleBuild(GhprbTrigger.java:296)
        at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:80)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:325)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:318)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:161)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:174)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:154)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:287)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecut
or.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java
:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

x-ref kubernetes/kubernetes/issues/22435, which is documenting all our PRs which failed to run.

**Comment by ixdy** [comment]
I was also seeing lots of "Trigger only phrase but we are not triggered" in the log, which is probably related to this (and also a fantastically unhelpful error message).

**Comment by DavidTanner** [comment]
I need to fix a test and get another PR merged so I can do releases again, then I will address this.  The NPE is actually a simple fix.

**Comment by ehberger** [comment]
This has been causing a bunch of issues for us.  We are prior users of GHPRB plugin, so we know how awesome it is, but with this pull it's so flaky that it was basically unusable until we figured out that this was causing the problem.

+1 on prioritizing a fix for this please.
