### ISSUE TITLE
Rate limit + lots of pull requests == inaccessible Jenkins

### ISSUE THREAD

**Issue by mmitche** [jenkinsci/ghprb-plugin#307]
I saw a failure yesterday where the Jenkins HTTP interface became inaccessible.  What appears to have happened is that a thread hit the GIthub rate limit while handling the pull request hook.  This caused a sleep timer to fire in the call stack and the thread waited around.  While that was waiting, more requests came in (some from the same PR, some from others) and also hit the rate limit.  Each thread blocked and then HTTP handler queue filled up and the whole thing ground to a halt.

**Comment by mmitche** [comment]
"Handling POST /ghprbhook/ from 192.30.252.34 : RequestHandlerThread[#1109]" daemon prio=10 tid=0x00007fe200393800 nid=0x5c92 waiting on condition [0x00007fe1591cd000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.kohsuke.github.RateLimitHandler$1.onError(RateLimitHandler.java:38)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:518)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:418)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:389)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.kohsuke.github.PagedIterable.asList(PagedIterable.java:42)
	at org.kohsuke.github.GHIssue.getComments(GHIssue.java:200)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.checkComments(GhprbPullRequest.java:395)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.updatePR(GhprbPullRequest.java:215)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:155)

**Comment by DavidTanner** [comment]
I am working on a fix, where once we decide to keep the event and send it to the triggers we start a new thread.  I am having issues getting it to work at the moment though, but I will work on it some more tonight.

**Comment by mmitche** [comment]
One way to work around this, btw, is to increase the number of handler threads so that it's less likely to clog up the HTTP queue. The default is pretty low (I think it's 32)
