### ISSUE TITLE
Null pointer exception when attempting to build:

### ISSUE THREAD

**Issue by csaintc** [jenkinsci/ghprb-plugin#332]
After my build executes successfully, I get this error message:
```
18:36:39 npm info ok 
18:36:39 ERROR: Build step failed with exception
18:36:39 java.lang.NullPointerException
18:36:39 	at org.jenkinsci.plugins.github.pullrequest.publishers.impl.GitHubPRBuildStatusPublisher.perform(GitHubPRBuildStatusPublisher.java:92)
18:36:39 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
18:36:39 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
18:36:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
18:36:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
18:36:39 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
18:36:39 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
18:36:39 	at hudson.model.Run.execute(Run.java:1763)
18:36:39 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:36:39 	at hudson.model.ResourceController.execute(ResourceController.java:98)
18:36:39 	at hudson.model.Executor.run(Executor.java:410)
18:36:39 Build step 'GitHub PR: set PR status' marked build as failure
18:36:39 Setting status of 0241b63c11a21b6e42b3dcdd8572fe4e690d884f to FAILURE with url 
[secret] and message: 'Build finished. '
18:36:40 Finished: FAILURE
```

I'm on Jenkins 2.1

**Comment by csaintc** [comment]
Image of config:

![image](https://cloud.githubusercontent.com/assets/907929/15025554/70765192-11ff-11e6-91de-df031998f43c.png)

**Comment by DavidTanner** [comment]
If I am reading your config right, you are actually trying to set up a Post-Build action, which is not part of this plugin.  Also looking at the stack trace, nothing from this plugin is in the trace.

**Comment by csaintc** [comment]
This isn't this plugin?
```
18:36:39    at org.jenkinsci.plugins.github.pullrequest.publishers.impl.GitHubPRBuildStatusPublisher.perform(GitHubPRBuildStatusPublisher.java:92)
```

**Comment by DavidTanner** [comment]
No, the package for this is org.jenkinsci.plugins.ghprb
