### ISSUE TITLE
FileNotFoundException when using comment file path

### ISSUE THREAD

**Issue by hidroh** [jenkinsci/ghprb-plugin#343]
I'm trying to use comment file path to add comment to PRs with some analysis results read from a text file that has previously been created during build phase. According to build log, reading comment file seems to be the last build step that was executed, which means the file should already exist at that point, but I still get `FileNotFoundException`. The path I use is `${WORKSPACE}/path/to/comment/file` and I double check to make sure it exists.

The job was executed on a remote slave machine, which is connected by Jenkins master via SSH. I suspect the plugin was trying to read a file on Jenkins master and thus couldn't find the file, whose path is meant for the slave machine, but I could be wrong.

Some context:
- Jenkins version: 1.651.1
- Gihub plugin version: 1.18.1
- Github API plugin version: 1.72.1
- Github authentication plugin version: 0.22.3
- GHPRB plugin version: 1.31.2

Full stack trace:

```
Couldn't read comment file
java.io.FileNotFoundException: File '/var/slave/workspace/job/lint-results.txt' does not exist
    at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
    at org.jenkinsci.plugins.ghprb.extensions.comments.GhprbCommentFile.postBuildComment(GhprbCommentFile.java:45)
    at org.jenkinsci.plugins.ghprb.GhprbBuilds.commentOnBuildResult(GhprbBuilds.java:227)
    at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:202)
    at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
    at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
    at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
    at hudson.model.Run.execute(Run.java:1783)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)

!!! Couldn't read commit file !!!
```

**Comment by hidroh** [comment]
May be related to #45 as well.

**Comment by SVilgelm** [comment]
Ok. I investigated a little bit into this problem. It happens if the build starts on a slave, on a master node everything works fine.

**Comment by Serjster** [comment]
This could also happen if any of the folders in the path have a space in them.

**Comment by jrudolph** [comment]
Seems like this should be implemented similar to how the JUnit test report plugin is picking up files from the workspace: https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/hudson/tasks/junit/JUnitParser.java#L103

**Comment by reverson** [comment]
@jrudolph Has this been merged with the jenkinsci version? I'm on the latest ghprb within the Jenkins plugin manager, but I am still seeing this issue.

**Comment by jrudolph** [comment]
No, the open PR is here: https://github.com/jenkinsci/ghprb-plugin/pull/512

**Comment by anilaraveti** [comment]
I an new in Jenkins i am trying to exceute jenkins pipeline but i am getting below error 
https://github.com/anilaraveti/GIT_PIPLINE this is git hub added this one jenkins pipline 


Started by user anil
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:167)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:159)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:159)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:295)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

let me know how to proceed further
