### ISSUE TITLE
UpdateStatus Request fails (doesn't use Auth-Token)

### ISSUE THREAD

**Issue by jelmd** [jenkinsci/ghprb-plugin#363]
I wondered, why we always get something like:
```
...
07:44:49 java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
07:44:49 	at org.kohsuke.github.Requester.handleApiError(Requester.java:590)
07:44:49 	at org.kohsuke.github.Requester._to(Requester.java:267)
07:44:49 	at org.kohsuke.github.Requester.to(Requester.java:208)
07:44:49 	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:871)
07:44:49 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:273)
07:44:49 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:186)
07:44:49 	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:132)
...
```
This is Jenkins  2.7 with ghprb-1.32.4 and github-api-1.75.
Digging a little bit deeper revealed, that the Authorization header incl. Token (which has repo:status included) is not send in status update and probably therefore it fails.

**Comment by jelmd** [comment]
Correction: 'uc.getRequestProperties()' doesn't return all RequestProperty entries actually being set - it hides some, like 'Authorization'. However, setting the logger for 'sun.net.www.protocol.http.HttpURLConnection' to 'ALL' causes it to show _all_ headers, and there we can see, that the 'Authorization' header is used as expected. So the bug is probably on the github server side?
```
POST /repos/foo/foo/statuses/00f19478fb4a5e508d9e53a702283bbd25c5cc73 HTTP/1.1
Authorization: token 0123456789abcdef0123456789abcdef01234567
Accept-Encoding: gzip
Content-type: application/x-www-form-urlencoded
User-Agent: Java/1.8.0_45-internal
Host: api.github.com
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 122

{target_url=http://come.home:8080/job/foo-PRs/29/, description=Build started sha1 is merged., state=pending}
```
```
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Wed, 15 Jun 2016 18:16:39 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4951
X-RateLimit-Reset: 1466016043
X-OAuth-Scopes: public_repo, read:org, read:repo_hook, repo:status, user:email
X-Accepted-OAuth-Scopes:
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Content-Encoding: gzip
X-GitHub-Request-Id: 8D2C185A:1C0C2:19CC89AE:57619B87
```

**Comment by benpatterson** [comment]
This looks like a credentials issue

**Comment by benpatterson** [comment]
Well-written issue but the 404 implies to me that it's an issue with credentials either with the token being used, or with the repo. I'm closing for now as I do a sweep of older issues.

**Comment by doublesharp** [comment]
@benpatterson @jelmd I just got this exact error and opened an issue for it, however I ended up fixing it by renaming the repository and then changing it back to the original value, so it seemed to in fact be on the Github side of things. 

More details here: https://issues.jenkins-ci.org/browse/JENKINS-40359
