### ISSUE TITLE
[CRASH] java.lang.NullPointerException

### ISSUE THREAD

**Issue by XBeg9** [jenkinsci/ghprb-plugin#393]
After I made copy of one project I am getting this always on each save!

```Caused by: java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbRepository.hookExist(GhprbRepository.java:270)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createHook(GhprbRepository.java:289)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:260)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:66)
	at hudson.model.AbstractProject.submit(AbstractProject.java:1884)
	at hudson.model.Project.submit(Project.java:230)
	at hudson.model.Job.doConfigSubmit(Job.java:1246)
	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:796)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)```

**Comment by DotComing** [comment]
Seemed the same with me, you may update to the newest release, and at least you will save successfully, and to see what's next.

**Comment by XBeg9** [comment]
@DotComing I removed automatic handling of hooks... now it saves and it seems to work normal.
