### ISSUE TITLE
ghprbPullLongDescription is passed unescaped to 'ant', leads to code execution

### ISSUE THREAD

**Issue by arnaud-lb** [jenkinsci/ghprb-plugin#410]
When a pull request description contains characters like the backtrick, $, etc; they are interpreted by the shell.

For instance, I had a pull request with a description like this:

```
Fix `someThing`
```

The 'invoke ant' task is executing ant like this:

```
ant -file build.xml -DghprbCommentBody=null ... "-DghprbPullLongDescription=Fix `someThing`" ...
```

And the output:

```
/usr/bin/ant: 1: eval: someThing: not found
```

**Comment by benpatterson** [comment]
Looks like a duplicate of #327

**Comment by ntherning** [comment]
This is not a duplicate of #327. Not escaping backticks in e.g. `ghprbPullLongDescription` allows arbitrary code execution on the jenkins server. This is a very serious security problem. #556 has more details.

**Comment by andreyzh** [comment]
Yepps, been facing the same problem. We've had a PR with long description of:
Fixed Bug where Users could assign arbitary "Article Type" Data Category while updating a Knowledge Article.

Which has resulted in error:
Target "Type"" Data Category while updating a Knowledge Article." does not exist in the project "SalesForce Build Automation Tools". 
	at org.apache.tools.ant.Project.tsort(Project.java:1912)
	at org.apache.tools.ant.Project.topoSort(Project.java:1820)
	at org.apache.tools.ant.Project.topoSort(Project.java:1783)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:809)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
