### ISSUE TITLE
ghprb fails to build after forced push to branch of a PR

### ISSUE THREAD

**Issue by feliperoos** [jenkinsci/ghprb-plugin#418]
Hi,

I've rebase master into a branch and ended up having to force push the branch to get the update going. The PR on github for that branch was ok with that, but ghprb failed to build after I've done it. I've tried to close the PR and create a new one from the branch, still have the same error.

Thanks in advange for any support on this.

GitHub pull request #122 of commit d18bd52eef5157cad8a8fcd0cef8127b5a95ad64, no merge conflicts.
Setting status of d18bd52eef5157cad8a8fcd0cef8127b5a95ad64 to PENDING with url <REMOVED>/397/ and message: 'Build started sha1 is merged.'
Building on master in workspace /data/jenkins/jenkins/jobs/<REMOVED>/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@<REMOVED>.git # timeout=10
Fetching upstream changes from git@<REMOVED>.git
 > git --version # timeout=10
 > git fetch --tags --progress git@<REMOVED>.git +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/122/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/122/merge^{commit} # timeout=10
Merging Revision d3b22ee42ef3535da5e92cda7721e4e1c7a79acf (refs/remotes/origin/pr/122/merge) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > git rev-parse origin/master^{commit} # timeout=10
FATAL: Command "git rev-parse origin/master^{commit}" returned status code 128:
stdout: origin/master^{commit}

stderr: fatal: ambiguous argument 'origin/master^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse origin/master^{commit}" returned status code 128:
stdout: origin/master^{commit}

stderr: fatal: ambiguous argument 'origin/master^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1752)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1725)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1721)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1391)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1403)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:685)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:64)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:994)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1083)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of d18bd52eef5157cad8a8fcd0cef8127b5a95ad64 to FAILURE with url <REMOVED>/397/ and message: 'Build finished. '

**Comment by benpatterson** [comment]
Looks like #414
