### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by buggyb12** [jenkinsci/ghprb-plugin#433]
Sending build status INPROGRESS for commit 97582dbfdba41ce078999d50dc5813634c182e50 to BitBucket is done!
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:401)

Build step 'Salesforce Migration Assistant' marked build as failure
Sending build status FAILED for commit 97582dbfdba41ce078999d50dc5813634c182e50 to BitBucket is done!
Finished: FAILURE

**Comment by hlopetz** [comment]
hi @buggyb12,

could you please clarify how/if it is fixed just because i experience the same issue with the same [SMA plugin](https://github.com/jenkinsci/salesforce-migration-assistant-plugin).

thanks!

**Comment by neetiks** [comment]
Soultion is mentioned in -https://github.com/jenkinsci/salesforce-migration-assistant-plugin/issues/11 
Updated plugin
