### ISSUE TITLE
Unable to fetch origin - Workspace corruption? 

### ISSUE THREAD

**Issue by MasterSlowPoke** [jenkinsci/ghprb-plugin#466]
Hello, I've been trying to use this plugin to run jenkins on new pull requests, and initially I was successful. However, after a short period of time (fifteenish minutes), it would being crashing on new requests with this error:

```
Building in workspace /var/lib/jenkins/jobs/Libras Pull Requests/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:71lbs/libras.git # timeout=10
Fetching upstream changes from git@github.com:71lbs/libras.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress git@github.com:71lbs/libras.git refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:71lbs/libras.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:803)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1063)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1094)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
       and etc...
```

The only way I was able to get it working again is by deleting the job's workspace, and have it pull down a fresh clone. Is there any settings that I can use to get to always pull down a fresh clone, or is this some sort of error with the plugin?

**Comment by benpatterson** [comment]
Craig... Is there more to the stacktrace?

Can you go directly into the worker and attempt to git pull?

Offhand I can't think of anything obvious...

**Comment by MasterSlowPoke** [comment]
Here's the full stacktrace, sorry for cutting it off:

```

 > git fetch --tags --progress git@github.com:71lbs/libras.git refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:71lbs/libras.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:803)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1063)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1094)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1729)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress git@github.com:71lbs/libras.git refs/pull/*:refs/remotes/origin/pr/*" returned status code 1:
```

I'm able to get it to run by setting a pre-build step of cleaning up the workspace, but ideally that wouldn't be necessary.

I'm still pretty new to Jenkins, so I'm not sure how to go directly into the worker.

**Comment by benpatterson** [comment]
I'd be surprised if this impacts a fetch call, but I'm wondering if there is anything being left behind that would pose a conflict?

As for getting onto the worker, if you have a basic set-up you would just have the master instance. You could SSH onto that, sudo as jenkins and try these commands and see if you get more out of the git output. Sorry I can't be more help...it looks to me like it is moreso the git configuration than the ghprb itself.

**Comment by vincedjango** [comment]
@MasterSlowPoke 

I had exactly the same stack trace with this error message: "ERROR: Error fetching remote repo 'origin'"
I was getting it as soon as my repository in GitHub was set to private. Everything was configured correctly in Jenkins and Github.

I searched for days and surprisingly, this worked, no Jenkins restart is even required:
https://stackoverflow.com/a/37753202/5484068

`#I was on Windows Server 2012 R2, open a CMD in your Jenkins installation as an Admin, and run this:`
`git config --global --unset credential.helper`
`git config --system --unset credential.helper`

**Comment by luminescent** [comment]
Thank you, @vincedjango . This fixed one of my problems on Ubuntu. So your solution is not restricted to Windows installations.

**Comment by flipnovidade** [comment]
git config --system --unset credential.helper

error: could not lock config file /etc/gitconfig: Permission denied

**Comment by AdamJLemmon** [comment]
@flipnovidade `sudo git config --system --unset credential.helper`

**Comment by AdamJLemmon** [comment]
Was having the exact same problem and the above did not work.

Solution for me was to clear the workspace dir @ `/var/lib/jenkins/workspace/*`

**Comment by myu8tbgl** [comment]
i have encountered the same error, i have tried both solution proposed above but still could not resolve the problem. Anyone could give any further suggestion?
=================
Cloning the remote Git repository
Cloning repository git@github.com:XXXXX/yyyyyyyy
 > git init /var/lib/jenkins/workspace/XXXXX_yyyyyyyy_dev-AGDDFTC2ZP23THKIP7FEBDRPRXF44PPITX4ID7CTIJKEFWRUZ7NA # timeout=10
Fetching upstream changes from git@github.com:XXXXX/yyyyyyyy
 > git --version # timeout=10
using GIT_ASKPASS to set credentials fetch credential for XXXXX
 > git fetch --tags --progress git@github.com:XXXXX/yyyyyyyy +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress git@github.com:XXXXX/yyyyyyyy +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1120)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
    at hudson.security.ACL.impersonate(ACL.java:290)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
=================

**Comment by myu8tbgl** [comment]
@kheaactua , sorry for the late update. i have resolved it. there actually no issue. my outgoing port was blocked by company firewall. so false alarm :) hope this is the case for u as well.

**Comment by kheaactua** [comment]
@myu8tbgl thanks for the reply.  Nah, my stuff is all internal.. Unfortunately it seems I'll have to simply continue with a deprecated 2014 version of git for windows - for now at least.

**Comment by nalingarg2** [comment]
I saw the same issue recently. For new this happened when I tried to build from a specific branch in the following order :
1. master (worked fine)
2. feature-branch(worked fine)
3. master (ERROR: Error fetching remote repo 'origin')
4. +refs/heads/master(worked fine)
5. master (worked again)
I do not understand the error. but this makes me feel that I did something silly that made my "master" unstable. I did make a lot of commits between step 1 and 3. I am guessing "+refs/heads/master" is a better way to do things when dealing with many branches.

**Comment by nbgucer** [comment]
The same issue can be seen when the remote Git password is changed. We have simply changed the credentials-id to resolve the issue.

**Comment by reitzig** [comment]
FWIW, I saw a similar error when new revisions where pushed while the build was running (stages running on other agents check out anew).

**Comment by ntufnel11** [comment]
We have resolved a similar error by verifying that the user has valid ssh keys in place, checking that the permissions on these files is not too open, and deleting the workspace. We had a .tmp folder in the workspace that was owned by an unknown user and we had to change ownership to allow us to delete it and rerun the build with success. 

using GIT_SSH to set credentials 
ERROR: Error fetching remote repo 'origin'

**Comment by dallasclouddev** [comment]
We have the same issue on CentOS Linux. Tried the above solutions but they did not work. 
Here is error:
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from ssh://git@proxy.git.sabre.com/shsat/platform-services.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: hudson.plugins.git.GitException: Command "/usr/local/git/bin/git fetch --no-tags --progress ssh://git@../platform-services.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 1:
stdout: 
stderr: remote: Total 0 (delta 0), reused 0 (delta 0)        
error: cannot lock ref 'refs/remotes/origin/US898839/DashboardSonarIssues': 'refs/remotes/origin/US898839' exists; cannot create 'refs/remotes/origin/US898839/DashboardSonarIssues'
From ssh://proxy.git.sabre.com/shsat/platform-services
 ! [new branch]      US898839/DashboardSonarIssues -> origin/US898839/DashboardSonarIssues  (unable to update local ref)
error: some local refs could not be updated; try running
 'git remote prune ssh://git@projectName.git' to remove any old, conflicting branches

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:892)
Each of the following 2 workarounds resolved the issue:
1. Use the Git client directly in the Jenkins pieline script:
 steps {
                sh "git clone ${gitProjectUrl}"
                dir("ui-dashboard") {
                    sh "git checkout ${params.branch}"
                }
            }
or
2. Delete the branch specified in the error output error: cannot lock ref 'refs/remotes/origin/US898839/DashboardSonarIssues':

**Comment by Mukhtarali212** [comment]
> @myu8tbgl Same. I've purged the workspaces, purged the project, re-installed Git on the slave, upgraded Jenkins from ~1.6 to 2.118, purged jenkins on the slave (as far as I know at least) and re-installed it, deleted the node and re-created it. From the shell on my slave (both cmd and WSL) I'm able to ssh to my git server (`ssh git@mygitserver`) without issue, etc..
> 
> And yet my projects' console output still report the git permission issues.
> 
> This all started around the time I upgraded from ~1.7 to 2.17 on my slave. After 2 days, I downgraded to the now deprecated version, and it seems to have fixed the problem.

you are using windows vm ..
