### ISSUE TITLE
DSL testing - tries to create webhooks

### ISSUE THREAD

**Issue by DukeyToo** [jenkinsci/ghprb-plugin#500]
When using job DSL with github hooks, and testing the pattern found at https://github.com/jenkinsci/job-dsl-plugin/wiki/Testing-DSL-Scripts , I am finding that there are a lot of errors thrown because executing the DSL in the test harness still tries to create webhooks.  An example partial stacktrace:

```
SEVERE: Could not retrieve GitHub repository named myorg/myrepo (Do you have properly set 'GitHub project' field in job configuration?)
    java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    	at org.kohsuke.github.Requester.handleApiError(Requester.java:603)
    	at org.kohsuke.github.Requester._to(Requester.java:283)
    	at org.kohsuke.github.Requester.to(Requester.java:224)
    	at org.kohsuke.github.GitHub.getRepository(GitHub.java:369)
    	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:112)
    	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:401)
    	at org.jenkinsci.plugins.ghprb.GhprbRepository.hookExist(GhprbRepository.java:269)
    	at org.jenkinsci.plugins.ghprb.GhprbRepository.createHook(GhprbRepository.java:292)
    	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:266)
    	at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:66)
```

While the tests still pass, they would be quicker and cleaner if this did not occur.  Is there some way to prevent this behavior?

**Comment by DukeyToo** [comment]
I created a workaround for this in my DSL code.  I set a variable in groovy code:

```
testing = System.properties.any { it.key =~ /org\.gradle\.test\.worker/ }
```

This sets the boolean `testing` value to be true when the DSL is being run via a gradle test.

Then, in my DSL block for gh-prb, I can have `useGitHubHooks(!testing)`, i.e. don't setup hooks when testing.
