### ISSUE TITLE
Intermittent but failures to check mergeability

### ISSUE THREAD

**Issue by ehberger** [jenkinsci/ghprb-plugin#516]
We are seeing failure to check mergeable status, frequently but not always.  Retest phrases seem to be working well, but initial PR creation seems to frequently be problematic.

This feels like potentially just an ordering issue that could be fixed with waiting and a retry, since when I've come back after the fact for any given failure I've been able to successfully make the failed request manually with the same user the GHPRB runs as.

Error logs look like:
```
PR is not null, checking if mergable
May 05, 2017 8:35:44 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbPullRequest checkMergeable
Couldn't obtain mergeable status.
java.io.FileNotFoundException: https://api.github.com/repos/desmosinc/pillow/pulls/7704
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:586)
Caused: java.io.FileNotFoundException: https://api.github.com/repos/desmosinc/pillow/pulls/7704
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1677)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1673)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1246)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:596)
	at org.kohsuke.github.Requester._to(Requester.java:262)
Caused: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:650)
	at org.kohsuke.github.Requester._to(Requester.java:283)
	at org.kohsuke.github.Requester.to(Requester.java:231)
	at org.kohsuke.github.GHPullRequest.populate(GHPullRequest.java:207)
	at org.kohsuke.github.GHPullRequest.getMergeable(GHPullRequest.java:170)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.checkMergeable(GhprbPullRequest.java:514)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:378)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:163)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:382)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:627)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:252)
```

We're triggering based on webhooks, using a private repo but hosted by Github, and have multiple jobs triggering off of the same repo's PRs.

**Comment by atsalolikhin-spokeo** [comment]
We are seeing this error as well now in 2023.
