### ISSUE TITLE
Could not update commit status of Pull Request on Github

### ISSUE THREAD

**Issue by ns-phennessy** [jenkinsci/ghprb-plugin#532]
We are seeing the following stack trace when running builds off of pull requests. It has been working fine for months and we have not changed anything with our setup. Any insights would be helpful

We are using version `1.36.2` of this plugin

```Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"target_url","message":"target_url must use http(s) scheme"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:654)
	at org.kohsuke.github.Requester._to(Requester.java:283)
	at org.kohsuke.github.Requester.to(Requester.java:224)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1000)
	at org.****ci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
	at org.****ci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:185)
	at org.****ci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:130)
	at org.****ci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:18)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 422, message: 'Unprocessable Entity' for URL: https://api.github.com/repos/ORGNAMEHIDDEN/REPONAMEHIDDEN/statuses/SHA1HASHHERE
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	at org.kohsuke.github.Requester._to(Requester.java:262)
	... 11 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/ORGNAMEHIDDEN/REPONAMEHIDDEN/statuses/SHA1HASHHERE
	at sun.reflect.GeneratedConstructorAccessor147.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1677)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1673)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1246)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:596)
	... 12 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/ORGNAMEHIDDEN/REPONAMEHIDDEN/statuses/SHA1HASHHERE
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:586)
	... 12 more```

**Comment by benpatterson** [comment]
I'm assuming you likewise have not changed the plugin version?

Hmm it looks like it's coming from the github-api plugin, but it could also
be a change in github itself...

**Comment by ns-phennessy** [comment]
Okay i'll try updating my plugins to latest

Any suggestions for debugging what is coming from github?

**Comment by ns-phennessy** [comment]
Was able to confirm it is an issue on Jenkins side

Posted to the status endpoint with a bogus "target_url" and it returns the same message:
```{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Status",
      "code": "custom",
      "field": "target_url",
      "message": "target_url must use http(s) scheme"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/statuses/#create-a-status"
}
```

Wondering where the error is actually occuring; and if there is any way i can extract what it is trying to send

**Comment by benpatterson** [comment]
Thanks for the update. Hmm were you able to successfully post to the same
endpoint and get a success message? I'm still not sure it's the plugin.

**Comment by ns-phennessy** [comment]
This is what i passed in: `{"state": "success", "target_url": "123", "description":"patdflkjfsa", "context": "default"}` which results in an error

however if i write a well-formed `target_url` it does work correctly. So it looks like it's failing Github's server side validation; which makes me think that Jenkins is sending some bogus value for target_url. Interestingly enough; putting no value in is a success.

**Comment by ns-phennessy** [comment]
So i found the offending lines:
https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java#L245-L247

We never had a `BUILD_URL` set. It appears that the value in there is irrelevant however.

**Comment by benpatterson** [comment]
Interesting. Did you happen to catch if you had any special characters in
your setting before you fixed it? Thanks a lot for pointing out the offense.

**Comment by HomemBravo** [comment]
Any update here?

**Comment by ns-phennessy** [comment]
To my knowledge this is not fixed.

I created a environment global environment variable `BUILD_URL` and left it blank and it appears to have "fixed" it for us for now.

**Comment by cristiangiagante** [comment]
I have the same issue, some news about this?
