### ISSUE TITLE
FileNotFoundException when retrieving commits for pull request

### ISSUE THREAD

**Issue by dsinang** [jenkinsci/ghprb-plugin#559]
Jenkins 2.46.3
GitHub Pull Request Builder 1.39.0
GitHub API Plugin 1.86

Whenever I create a pull request on Github, we run into this error 👍 

```
java.io.FileNotFoundException: https://api.github.com/repos/MassMedicalSociety/nejm-imc/pulls/28/commits
```

Using Postman, I'm able to retrieve results for https://api.github.com/repos/MassMedicalSociety/nejm-imc/pulls/28/commits if I use Basic authentication.

The relevant logs are shown below.

What could I be doing wrong ?

```
Received PushEvent for https://github.com/MassMedicalSociety/nejm-imc from 192.30.252.41 ⇒ http://jenkins.nejmgroup-dev.org/github-webhook/
Aug 10, 2017 5:35:03 PM INFO org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber$1 run
Poked nejm-imc-deploy-to-s3
Aug 10, 2017 5:35:03 PM WARNING org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
Request not known for event: push
Aug 10, 2017 5:35:15 PM WARNING org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
Request not known for event: push
Aug 10, 2017 5:35:15 PM INFO org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
Received PushEvent for https://github.com/MassMedicalSociety/nejm-imc from 192.30.252.42 ⇒ http://jenkins.nejmgroup-dev.org/github-webhook/
Aug 10, 2017 5:35:15 PM INFO org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber$1 run
Poked nejm-imc-deploy-to-s3
Aug 10, 2017 5:36:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
Checking PR #28 for MassMedicalSociety/nejm-imc
Aug 10, 2017 5:36:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
Checking PR #28 for job NEJM-INTERACTIVES/deploy-imc-pull-request
Aug 10, 2017 5:36:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #28 on MassMedicalSociety/nejm-imc by dsinang () updated at: 8/10/17 5:36 PM SHA: 92976252a0c37c8e86f09bd9972cb4f57cfcaee4
Aug 10, 2017 5:36:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #28 was updated on repo MassMedicalSociety/nejm-imc but there aren't any new comments nor commits; that may mean that commit status was updated.
Aug 10, 2017 5:36:04 PM SEVERE hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
A thread (Thread-145/2775) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.io.FileNotFoundException: https://api.github.com/repos/MassMedicalSociety/nejm-imc/pulls/28/commits
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:592)
Caused: java.io.FileNotFoundException: https://api.github.com/repos/MassMedicalSociety/nejm-imc/pulls/28/commits
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	at org.kohsuke.github.Requester.parse(Requester.java:584)
	at org.kohsuke.github.Requester.access$200(Requester.java:70)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:496)
Caused: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:660)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:501)
Caused: java.lang.Error
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:507)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:472)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getPRCommitAuthor(GhprbPullRequest.java:373)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:162)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:382)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:676)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:252)
```

bjoernhaeuser: Edited for readability

**Comment by bjoernhaeuser** [comment]
This normally means that the user you are using has no access rights to the PR.

**Comment by bjoernhaeuser** [comment]
If this is not the case, please reopen. :)
