### ISSUE TITLE
Expansion of ${sha1} in Branch specifier not working

### ISSUE THREAD

**Issue by sgronblo** [jenkinsci/ghprb-plugin#564]
I am trying to set up the Github Pull Request Builder plugin for our Jenkins server, however sadly the `${sha1} ` expansion in the Branch Specifier does not seem to be expanded before the git command is executed.

I can see from the "Console Output" that the ${sha1} is unexpanded in the resulting git command which means that the build fails immediately.

Some things I noticed:

1. `sha1` is included and seems to have the right value in the "Parameters" section of the build
2. the Jenkins wiki page for GHPRB at https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin lists `sha1` among the "useful environment variables" that are made available by the plugin
3. the "Branch Specifier" part of the "Pipeline" section in the job's configuration mentions that environment variables should be expandable

So based on the above, everything seems like it should work, except it doesn't.

Versions:

- Jenkins 2.60.3
- Github API plugin 1.86
- Github plugin 1.28.0
- Git plugin 3.5.1
- Credentials plugin 2.1.14
- Plain Credentials Plugin 1.4
- Github Pull Request Builder Plugin 1.39.0

**Comment by sgronblo** [comment]
I got this thing working today after switching away from using a Jenkinsfile/pipeline job to a simple shell script based job. Does that help in figuring out which piece is broken?

**Comment by bjoernhaeuser** [comment]
@sgronblo based on your description I would assume the problem is more in the Jenkinsfile / pipeline support. Suggesting to move the issue there :/

**Comment by dylex** [comment]
For the record, I had this same problem, which looks like this:
```
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/${sha1}:refs/remotes/origin/${sha1} --prune" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/heads/${sha1}
Unexpected end of command stream

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1689)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:380)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:351)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:196)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:172)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:99)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:59)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:262)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
```
And worked around it by disabling "lightweight checkout" in the pipeline config.

**Comment by usmichael** [comment]
In version `2.121.1` it's still happening. Solution presented by @dylex works!! 👍

**Comment by sklrsn** [comment]
@dylex thanks

**Comment by jinlxz** [comment]
@dylex thank you, I have the same issue, it works.

**Comment by dave-kennedy** [comment]
I don't see how disabling lightweight checkout is a viable solution. I don't want to have to clone my entire source tree just to use a parameter in my pipeline from SCM configuration.

**Comment by reach2jeyan** [comment]
@dylex  Sometimes smallest things in life gives you Nirvana . Thanks a ton
