### ISSUE TITLE
Numeric value (....) out of range of int

### ISSUE THREAD

**Issue by mattjmorrison** [jenkinsci/ghprb-plugin#579]
I just began running into this issue yesterday. When the commit status is being updated github's API returns an `id` that exceeds the maximum size of Java's `int`. The status is updated, but the response fails to be parsed because of this error and prevents the rest of the build from running. I couldn't find any other issues or PRs related to this - if you are aware of this issue being addressed elsewhere and could point me to it, that would be greatly appreciated.

Here is a stacktrace for context:

```
GitHub pull request #1 of commit 68a32394059e234a39be24f4fda5bc9e5eaaba79, no merge conflicts.
Setting status of 68a32394059e234a39be24f4fda5bc9e5eaaba79 to PENDING with url https://jenkins.imtapps.com/jenkins/job/apps.data.policy-dev/1/ and message: 'Build started sha1 is merged.'
Using context: apps.data.policy-dev
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/imtapps/apps.data.policy/statuses/68a32394059e234a39be24f4fda5bc9e5eaaba79
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1071)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:185)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:18)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1733)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:314)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/imtapps/apps.data.policy/statuses/68a32394059e234a39be24f4fda5bc9e5eaaba79","id":4295137950,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://jenkins.imtapps.com/jenkins/job/apps.data.policy-dev/1/","context":"apps.data.policy-dev","created_at":"2017-10-20T05:27:57Z","updated_at":"2017-10-20T05:27:57Z","creator":{"login":"imtapps-bot","id":28652499,"avatar_url":"https://avatars1.githubusercontent.com/u/28652499?v=4","gravatar_id":"","url":"https://api.github.com/users/imtapps-bot","html_url":"https://github.com/imtapps-bot","followers_url":"https://api.github.com/users/imtapps-bot/followers","following_url":"https://api.github.com/users/imtapps-bot/following{/other_user}","gists_url":"https://api.github.com/users/imtapps-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/imtapps-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imtapps-bot/subscriptions","organizations_url":"https://api.github.com/users/imtapps-bot/orgs","repos_url":"https://api.github.com/users/imtapps-bot/repos","events_url":"https://api.github.com/users/imtapps-bot/events{/privacy}","received_events_url":"https://api.github.com/users/imtapps-bot/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:618)
	... 13 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4295137950) out of range of int
 at [Source: {"url":"https://api.github.com/repos/imtapps/apps.data.policy/statuses/68a32394059e234a39be24f4fda5bc9e5eaaba79","id":4295137950,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://jenkins.imtapps.com/jenkins/job/apps.data.policy-dev/1/","context":"apps.data.policy-dev","created_at":"2017-10-20T05:27:57Z","updated_at":"2017-10-20T05:27:57Z","creator":{"login":"imtapps-bot","id":28652499,"avatar_url":"https://avatars1.githubusercontent.com/u/28652499?v=4","gravatar_id":"","url":"https://api.github.com/users/imtapps-bot","html_url":"https://github.com/imtapps-bot","followers_url":"https://api.github.com/users/imtapps-bot/followers","following_url":"https://api.github.com/users/imtapps-bot/following{/other_user}","gists_url":"https://api.github.com/users/imtapps-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/imtapps-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imtapps-bot/subscriptions","organizations_url":"https://api.github.com/users/imtapps-bot/orgs","repos_url":"https://api.github.com/users/imtapps-bot/repos","events_url":"https://api.github.com/users/imtapps-bot/events{/privacy}","received_events_url":"https://api.github.com/users/imtapps-bot/received_events","type":"User","site_admin":false}}; line: 1, column: 129]
 at [Source: {"url":"https://api.github.com/repos/imtapps/apps.data.policy/statuses/68a32394059e234a39be24f4fda5bc9e5eaaba79","id":4295137950,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://jenkins.imtapps.com/jenkins/job/apps.data.policy-dev/1/","context":"apps.data.policy-dev","created_at":"2017-10-20T05:27:57Z","updated_at":"2017-10-20T05:27:57Z","creator":{"login":"imtapps-bot","id":28652499,"avatar_url":"https://avatars1.githubusercontent.com/u/28652499?v=4","gravatar_id":"","url":"https://api.github.com/users/imtapps-bot","html_url":"https://github.com/imtapps-bot","followers_url":"https://api.github.com/users/imtapps-bot/followers","following_url":"https://api.github.com/users/imtapps-bot/following{/other_user}","gists_url":"https://api.github.com/users/imtapps-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/imtapps-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imtapps-bot/subscriptions","organizations_url":"https://api.github.com/users/imtapps-bot/orgs","repos_url":"https://api.github.com/users/imtapps-bot/repos","events_url":"https://api.github.com/users/imtapps-bot/events{/privacy}","received_events_url":"https://api.github.com/users/imtapps-bot/received_events","type":"User","site_admin":false}}; line: 1, column: 119] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1607)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at org.kohsuke.github.Requester.parse(Requester.java:616)
	... 13 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4295137950) out of range of int
 at [Source: {"url":"https://api.github.com/repos/imtapps/apps.data.policy/statuses/68a32394059e234a39be24f4fda5bc9e5eaaba79","id":4295137950,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://jenkins.imtapps.com/jenkins/job/apps.data.policy-dev/1/","context":"apps.data.policy-dev","created_at":"2017-10-20T05:27:57Z","updated_at":"2017-10-20T05:27:57Z","creator":{"login":"imtapps-bot","id":28652499,"avatar_url":"https://avatars1.githubusercontent.com/u/28652499?v=4","gravatar_id":"","url":"https://api.github.com/users/imtapps-bot","html_url":"https://github.com/imtapps-bot","followers_url":"https://api.github.com/users/imtapps-bot/followers","following_url":"https://api.github.com/users/imtapps-bot/following{/other_user}","gists_url":"https://api.github.com/users/imtapps-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/imtapps-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/imtapps-bot/subscriptions","organizations_url":"https://api.github.com/users/imtapps-bot/orgs","repos_url":"https://api.github.com/users/imtapps-bot/repos","events_url":"https://api.github.com/users/imtapps-bot/events{/privacy}","received_events_url":"https://api.github.com/users/imtapps-bot/received_events","type":"User","site_admin":false}}; line: 1, column: 129]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:286)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 17 more```

**Comment by mattjmorrison** [comment]
Sorry, I believe this is the issue: https://github.com/kohsuke/github-api/issues/387

**Comment by alexejk** [comment]
I actually think this is still an issue even in this plugin as just bumping dependency version does not work, and thus most likely requires some work on this plugin.

**Comment by akoeplinger** [comment]
Installing the updated github-api-plugin 1.90 on Jenkins fixed the issue for me.

**Comment by consueloel** [comment]
installing the updated github api plugin on jenkins did not resolve the issue for us

**Comment by ToeBee** [comment]
Note that depending on exactly where this error is happening, it may require updating other things as well. For example, after updating the github-api plugin in Jenkins, it was still failing. The failure happened when SonarQube went to add a comment to a pull request so we had to update the GitHub plugin in SonarQube as well.

**Comment by consueloel** [comment]
Tried what ToeBee said and it worked!! Thanks so much!

I updated sonarqube's plugin.

**Comment by taymoor89** [comment]
@akoeplinger thanks, it worked... very funny!!

**Comment by Tin-Nguyen** [comment]
@akoeplinger  thanks, it fixed my issue as well. Thanks

**Comment by damaarten** [comment]
I only saw version 1.89 of this plugin in my Jenkins Update Center page, while version  1.90 with the fix for this issue had already been released.
And clicking the blue 'Check Now' button at the bottom showed the page 'Checking updates...' that did not change for minutes.
It turns out that in the 'Advanced' tab of the 'Manage Plugins' page we had the 'Update Site URL' configured as 'http://...', while this should be 'https://...' nowadays.
After we changed this, the 'Check Now' button started working again, and we could install the new 1.90 Github API plugin, and the issue was solved.
Just noting this here, maybe it helps others.

**Comment by ixmatus** [comment]
> I only saw version 1.89 of this plugin in my Jenkins Update Center page, while version 1.90 with the fix for this issue had already been released.
> And clicking the blue 'Check Now' button at the bottom showed the page 'Checking updates...' that did not change for minutes.
> It turns out that in the 'Advanced' tab of the 'Manage Plugins' page we had the 'Update Site URL' configured as 'http://...', while this should be 'https://...' nowadays.
> After we changed this, the 'Check Now' button started working again, and we could install the new 1.90 Github API plugin, and the issue was solved.
> Just noting this here, maybe it helps others.

@damaarten thanks for leaving this note, we ran into the same thing.
