### ISSUE TITLE
Randomly when PRs are raised PR build does not start due to an exception in the plugin

### ISSUE THREAD

**Issue by anshbansal** [jenkinsci/ghprb-plugin#581]
This has been happening for a while. Seems that there is bug in the plugin. The stacktrace is as follows
```
A thread (Thread-484/1041410) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.Error: org.kohsuke.github.GHFileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request"}
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:516)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:481)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getPRCommitAuthor(GhprbPullRequest.java:373)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:162)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:382)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:676)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:252)
Caused by: org.kohsuke.github.GHFileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:686)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:510)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/MASKED/MASKED/pulls/MASKED/commits
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1725)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1723)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1721)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1292)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester.access$200(Requester.java:73)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:505)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/MASKED/MASKED/pulls/MASKED/commits
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1674)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 11 more
```

**Comment by martenson** [comment]
We see this on @galaxyproject too. Moreover I suspect this breaks the github hook connection and stops future builds.

**Comment by epic9x** [comment]
I've inherited a jenkins installation that is exhibiting this behavior as well, I haven't been able to determine if it's one of the symptoms or cause.  We were happily triggering builds from comments on pull requests, and then yesterday is stopped working, and the logs have this within the first few minutes after it stopped working. 

I've checked back over a year of logs and didn't see this happening before the plugin stopped working.   This seems to have happened after an upgrade to 1.39.0, and persisted after a downgrade back to 1.36.2.

**Comment by bjoernhaeuser** [comment]
Could it be that your github oauth access token does not have the right privileges?

**Comment by anshbansal** [comment]
@bjoernhaeuser  If that was the case then no PR would be built due to access issues. Right? This happens randomly. Most PRs get built but sometimes it just does not work. People make comments to retest but that does not work sometimes. Looking at the logs this exception is occurring in jenkins logs

**Comment by bjoernhaeuser** [comment]
I see. Do you rebase commits sometimes? Does this happen after rebase?

**Comment by anshbansal** [comment]
@bjoernhaeuser  No rebasing. We merge using --no-ff flag, and sometimes cherry-pick.

**Comment by bjoernhaeuser** [comment]
@anshbansal 

Can you please test this when the next version is released if this still happens to you?

**Comment by DranonJoD** [comment]
Using Jenkins ver. 2.89.2 and seeing this happen quite often recently as we open and close lot of PRs.
