### ISSUE TITLE
Issues with 64bit commit status id in github api plugin

### ISSUE THREAD

**Issue by abhishek-bidgely** [jenkinsci/ghprb-plugin#587]
GitHub prb  plugin uses github plugin to get commit status at the end of the build. It is failing and getting this error
com.fasterxml.jackson.core.JsonParseException: Numeric value (4295001555) out of range of int
 at [Source: {"url":"https://api.github.com/repos/organiztion/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}; line: 1, column: 134]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:286)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4295001555) out of range of int
 at [Source: {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context"}; line: 1, column: 134]
 at [Source: {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}; line: 1, column: 124] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1607)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at org.kohsuke.github.Requester.parse(Requester.java:616)
Caused: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}
	at org.kohsuke.github.Requester.parse(Requester.java:618)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1071)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:160)
Caused: org.jenkinsci.plugins.github.common.CombineErrorHandler$ErrorHandlingException
	at org.jenkinsci.plugins.github.common.CombineErrorHandler.handle(CombineErrorHandler.java:74)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:164)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1762)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

It looks like response from GitHub API contains id value 4295001555 that is bigger than int

Now this issue has been fixed in version 1.90 by this ticket. https://issues.jenkins-ci.org/browse/JENKINS-47601

Do we need a new release of this plugin with github api dependency version as 1.90 ?

**Comment by abhishek-bidgely** [comment]
Just realized someone has already raised a PR https://github.com/jenkinsci/ghprb-plugin/pull/584. Please suggest if this issue can be closed

**Comment by shevek** [comment]
+1

**Comment by Dyakovvn** [comment]
+1

**Comment by trgill** [comment]
+1

**Comment by bjoernhaeuser** [comment]
#589 is now merged and the fix will be available in the next release.

@shevek @Dyakovvn @trgill:

These "+1" comments are not really helping. If this is a review just use the review feature from github. Otherwise add your reaction in the first comment and/or subscribe to the issue on the right side.

**Comment by Bamieh** [comment]
@bjoernhaeuser sorry for the inconvenience, but do you have any clue when the next release is going to be? we are using this plugin in production so its critical to have our CI working. I'd be glad to offer any help if needed.
Thanks

**Comment by bjoernhaeuser** [comment]
I expect the new versio to be released soon. 

In the meantime you can just install the "github-api" plugin directly, which should also resolve the problem.
