### ISSUE TITLE
Jobs not triggered when "Use github hooks for build triggering" is checked

### ISSUE THREAD

**Issue by JavierCVilla** [jenkinsci/ghprb-plugin#603]
I'm facing the same problems mentioned in #260, my jenkins job gets triggered when I **don't** check the option *Use github hooks for build triggering*, but it does not when the options is checked. The only thing I change is that option. 

The version is 1.39.0, same mentioned by @wangqr [here](https://github.com/jenkinsci/ghprb-plugin/issues/260#issuecomment-336683405).

This is the log I get from the plugin:

```java
Nov 29, 2017 9:48:52 AM FINE org.jenkinsci.plugins.ghprb.GhprbRootAction

Got payload event: issue_comment

Nov 29, 2017 9:48:52 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction

Checking issue comment '@bot build please' for repo XXX/XX

Nov 29, 2017 9:48:52 AM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger

Retrieving triggers for repo [XXX/XX]

Nov 29, 2017 9:48:52 AM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger

Found project [my-jenkins-job-trigger] for webhook repo [XXX/XX]

Nov 29, 2017 9:48:52 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger handleComment

Checking comment on PR #61 for job my-jenkins-job-trigger

Nov 29, 2017 9:48:52 AM FINER org.jenkinsci.plugins.ghprb.GhprbRepository

Comment on issue #61 from GHUser@...login=JavierCVilla,location=...{myuserinfo}...: @bot build please
```
I've tried configuring the webhook for both the whole organization and for the specific project.

Any suggestions?

**Comment by admin4ek** [comment]
The same for me. I've tried to enable option "Use github hooks for build triggering" and it's not working. Also I've found the following error on GitHub side in the hook logs:

```
Cache-Control: no-cache,no-store,must-revalidate
Connection: close
Content-Length: 16815
Content-Type: text/html;charset=UTF-8
Date: Thu, 30 Nov 2017 14:04:25 GMT
Expires: 0
Server: Apache
Set-Cookie: JSESSIONID=EC63B6998140C5FD2EF4106B6DF4BD1D; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-Hudson: 1.395
X-Hudson-Theme: default
X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjjNjPn2USu0Y/SCroLFpxYaW3a5nQOSVA9riaZbwlfaw5puJ0BGrgKfwYGzyPl3QEhqyHW6VPX1VlNBqzm8y/obKR0UNLr+w5schBjnzuhKp9wTtMxCV6E4dVx3S61U2OdWu6JBdKGcHtL4FfR3uR36K7IdlGMeMAjmUIT0G/a03Gqxl1uzJWlrmSDKnICAssfMhIwgzgmD2R949vYMedNmXgBDuGxuGvHPkMZJdbEjr14gfCi6au2R8TZBZMlWOh8FStOof5aHsGa2/hspSN3k1YHoVi2RS2BijuPvav+aKNb7+mufm8acZWUo0qfVeD5k5pLz4yvEIWgRfE6gkXwIDAQAB
X-Jenkins: 2.73.3
X-Jenkins-Session: 3e616160
X-Robots-Tag: none
X-UA-Compatible: chrome=1
Body



  
  <!DOCTYPE html><html><head resURL="/static/3e616160" data-rooturl="" data-resurl="/static/3e616160">
    

    <title>Jenkins [Jenkins]</title><link rel="stylesheet" href="/static/3e616160/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/3e616160/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/3e616160";</script><script src="/static/3e616160/scripts/prototype.js" type="text/javascript"></script><script src="/static/3e616160/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/3e616160/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/3e616160/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/3e616160/scripts/yui/dom/dom-min.js"></script><script src="/static/3e616160/scripts/yui/event/event-min.js"></script><script src="/static/3e616160/scripts/yui/animation/animation-min.js"></script><script src="/static/3e616160/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/3e616160/scripts/yui/container/container-min.js"></script><script src="/static/3e616160/scripts/yui/connection/connection-min.js"></script><script src="/static/3e616160/scripts/yui/datasource/datasource-min.js"></script><script src="/static/3e616160/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/3e616160/scripts/yui/menu/menu-min.js"></script><script src="/static/3e616160/scripts/yui/element/element-min.js"></script><script src="/static/3e616160/scripts/yui/button/button-min.js"></script><script src="/static/3e616160/scripts/yui/storage/storage-min.js"></script><script src="/static/3e616160/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/3e616160/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" href="/static/3e616160/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/static/3e616160/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><meta name="viewport" content="width=device-width, initial-scale=1" /><script src="/adjuncts/3e616160/org/kohsuke/stapler/jquery/jquery.full.js" type="text/javascript"></script><script>var Q=jQuery.noConflict()</script><link rel="stylesheet" href="/plugin/jquery-ui/css/jquery-ui-1.8.9.custom.css" type="text/css" /><script src="/plugin/jquery-ui/js/jquery-ui-1.8.9.custom.min.js"></script><meta http-equiv="X-UA-Compatible" content="chrome=1" /><script>
      if(window.Prototype && JSON) {
        var _json_stringify = JSON.stringify;
        JSON.stringify = function(value) {
            var _array_tojson = Array.prototype.toJSON;
            delete Array.prototype.toJSON;
            var r=_json_stringify(value);
            Array.prototype.toJSON = _array_tojson;
            return r;
        };
     }  
   </script><script src="/plugin/extended-choice-parameter/js/selectize.min.js" type="text/javascript"></script><script src="/plugin/extended-choice-parameter/js/jsoneditor.min.js" type="text/javascript"></script><script src="/plugin/extended-choice-parameter/js/jquery.jsonview.min.js" type="text/javascript"></script><link rel="stylesheet" href="/plugin/extended-choice-parameter/css/jquery.jsonview.css" /><link rel="stylesheet" id="icon_stylesheet" href="/plugin/extended-choice-parameter/css/selectize.css" /><link rel="stylesheet" id="icon_stylesheet" href="/plugin/extended-choice-parameter/css/selectize.bootstrap2.css" /><link rel="stylesheet" id="theme_stylesheet" /><link rel="stylesheet" id="icon_stylesheet" /><script src="/static/3e616160/scripts/yui/cookie/cookie-min.js"></script><script src="/sounds/script" type="text/javascript"></script><script type="text/javascript" defer="defer">function _sounds_ajaxJsonFetcherFactory(onSuccess, onFailure) {
		return function() {
			new Ajax.Request("/sounds/getSounds", {
				parameters: { version: VERSION },
  				onSuccess: function(rsp) {
  					onSuccess(eval('x='+rsp.responseText))
  				},
  				onFailure: onFailure
  			});
  		}
	}
  	
  	if (AUDIO_CAPABLE) {
	  	_sounds_pollForSounds(_sounds_ajaxJsonFetcherFactory);
	}</script><script src="/static/3e616160/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam two-column jenkins-2.73.3" data-version="2.73.3"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/3e616160/images/headshot.png" alt="title" id="jenkins-head-icon" /><img src="/static/3e616160/images/title.png" alt="title" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"> <a href="/login?from=%2Fghprbhook%2F"><b>log in</b></a></div><div class="searchbox hidden-xs"><form method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="https://jenkins.io/redirect/search-box"><img src="/static/3e616160/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/3e616160/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/3e616160/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Jenkins</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"><div class="task"><a href="https://jenkins.io/" class="task-icon-link"><img src="/static/3e616160/images/24x24/next.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" /></a> <a href="https://jenkins.io/" class="task-link">Jenkins project</a></div><div class="task"><a href="https://jenkins.io/redirect/report-an-issue" class="task-icon-link"><img src="/static/3e616160/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" /></a> <a href="https://jenkins.io/redirect/report-an-issue" class="task-link">Bug tracker</a></div><div class="task"><a href="https://jenkins.io/redirect/mailing-lists" class="task-icon-link"><img src="/static/3e616160/images/24x24/search.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" /></a> <a href="https://jenkins.io/redirect/mailing-lists" class="task-link">Mailing Lists</a></div><div class="task"><a href="https://twitter.com/jenkinsci" class="task-icon-link"><img src="/static/3e616160/images/24x24/user.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" /></a> <a href="https://twitter.com/jenkinsci" class="task-link">Twitter: @jenkinsci</a></div></div><div id="main-panel"><a name="skip2content"></a><h1 style="text-align: center"><img src="/static/3e616160/images/rage.png" width="154" height="179" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://jenkins.io/redirect/issue-tracker">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="https://jenkins.io/redirect/users-mailing-list">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.getPullRequest(GhprbRootAction.java:267)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.handleEvent(GhprbRootAction.java:214)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.handleAction(GhprbRootAction.java:172)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:118)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.IndexDispatcher.dispatch(IndexDispatcher.java:26)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:765)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:232)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:209)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:113)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:592)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:403)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1366)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Nov 30, 2017 2:02:17 PM UTC</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="https://jenkins.io/">Jenkins ver. 2.73.3</a></span><script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"></script><script>CFInstall.check({mode: "overlay"});</script></div></div></div></footer></body></html>```

**Comment by JavierCVilla** [comment]
@bjoernhaeuser any ideas?

**Comment by bjoernhaeuser** [comment]
@JavierCVilla not out of my sleave ;) 

Can you paste the relevant content of the settings.xml of your build? (`<your build>/config.xml`) 

The plugin is than configured in the `triggers` section. Does the xml changes with and without the setting? 

Can you also look into the github hook config and manually delete the already setup hook on github?

**Comment by bjoernhaeuser** [comment]
@admin4ek 

This looks like you setup the wrong URL for the Hook. 

@JavierCVilla do you have any news around the configuration?
