### ISSUE TITLE
Unable to handle comment for PR

### ISSUE THREAD

**Issue by aleskiontherun** [jenkinsci/ghprb-plugin#629]
Just got this error when tried to trigger a PR build by posting a comment:
```
Feb 13, 2018 7:26:44 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
Checking issue comment 'test please' for repo xxxx/xxxx

Feb 13, 2018 7:26:44 PM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger handleComment
Checking comment on PR #xxxx for job xxxx

Feb 13, 2018 7:26:44 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #xxxx was updated/initialized on xxxx/xxxx at 2/13/18 7:26 PM by Aleksei Vesnin (comment)

Feb 13, 2018 7:26:45 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRootAction$1 run
Unable to handle comment for PR# xxxx, repo: xxxx/xxxx
java.lang.NullPointerException
	at org.kohsuke.github.GHPerson.populate(GHPerson.java:44)
	at org.kohsuke.github.GHPerson.getEmail(GHPerson.java:231)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getAuthorEmail(GhprbPullRequest.java:839)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:67)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:525)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:518)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:282)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:354)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:738)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:238)
```
Triggering by push works well.

Weird thing is that I have two different projects with two different GitHub organizations and two different Jenkins servers and get this error only on one of them. GHPRB plugin and the jobs are configured exactly the same. Only organization names, github credentials and sets of Jenkins plugins are different.

Jenkins 2.89.3
ghprb-plugin 1.40.0

Stumbled upon this commit to github-api https://github.com/kohsuke/github-api/commit/ab6253cbd0a0d82c72ce5e212a799c7d40c36755 which fixes the exception but not sure what causes it.

**Comment by eloycoto** [comment]
We have a similar issue, and I think that it's when a comment is deleted: 

- User creates a PR 
- User adds a comment to trigger a new PR comment-id: AAA
- Trigger works. 
- User deleted the comment
- New comment to trigger got an exception, and PR cannot be tested anymore

**Comment by dizeee** [comment]
Not related to deleted comments in our case.

**Comment by aldochristiaan** [comment]
@dizeee i got this on my jenkins server too, so how did you solve it ?

**Comment by nazaga** [comment]
Hi have the same error with:
Jenkins ver. 2.107.3
ghprb-plugin 1.42.0
any fix for that ?

**Comment by akashdhruv** [comment]
Any updates on how this can be resolved? Facing similar issues
