### ISSUE TITLE
GitHubPR Jenkins plugin is failing with SSL exceptions, using JAVA 1.7

### ISSUE THREAD

**Issue by skalangi-clh** [jenkinsci/ghprb-plugin#634]
```
Feb 24, 2018 2:09:00 AM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: Error while accessing rate limit API
org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/rate_limit
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:318)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:98)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:300)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 17 more
```

_@bjoernhaeuser edited for readability_

**Comment by etherge** [comment]
+1, got the same issue.

**Comment by etherge** [comment]
set JENKINS_JAVA_OPTIONS="-Dhttps.protocols=TLSv1.2" as a workaround

**Comment by junoteam** [comment]
@etherge thanks it works for us like this: 
```
vim /etc/default/jenkins
JAVA_ARGS="-Dhudson.diyChunking=false -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2"

```

**Comment by holybit** [comment]
Same issue here, however setting `JENKINS_JAVA_OPTIONS="-Dhttps.protocols=TLSv1.2"` did not fix the issue as we are still seeing SSL errors in the logs on all Github Pull Requests.

**Comment by bjoernhaeuser** [comment]
@holybit you are running a rather old version of the plugin, is thi intended?

To be honest, either you are going to upgrade to java 1.8 or set the mentioned tls options. There is not so much the plugin can do.

**Comment by bjoernhaeuser** [comment]
Closing this. Feel free to comment and we can open this issue again.
