### ISSUE TITLE
NullPointerException when getting build environment parameters

### ISSUE THREAD

**Issue by kotky** [jenkinsci/ghprb-plugin#642]
I have set up the plugin with private repository and it works fine with webhooks, starts the job with correct branch and everything, but for some reason it breaks when collecting the project build environment. Project is freestyle, parametrized and parameters are collected as they should. The issue is the same with manual project run.

`09-Mar-2018 10:03:09.649 INFO [Thread-12] org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR Checking PR #XX for job TEST-XX
09-Mar-2018 10:03:09.865 INFO [Thread-12] org.jenkinsci.plugins.ghprb.GhprbPullRequest.updatePR Pull request #57 was updated/initialized on XX/XX at 3/9/18 10:03 AM by XX (PR update)
09-Mar-2018 10:03:19.831 WARNING [Executor #0 for master : executing TEST-XX #XX] hudson.model.listeners.RunListener.report RunListener failed
 java.lang.NullPointerException
        at hudson.model.AbstractBuild.getBuildVariables(AbstractBuild.java:996)
        at org.jenkinsci.plugins.ghprb.Ghprb.getEnvVars(Ghprb.java:350)
        at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:248)
        at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:193)
        at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:144)
        at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:20)
        at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
        at hudson.model.Run.execute(Run.java:1723)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)`

Jenkins version is 2.109

**Comment by bjoernhaeuser** [comment]
How are you starting the build? If you do a manual build you would need to provide all the build variables. Projects which are triggered through this plugin should only be triggered through it.
