### ISSUE TITLE
Status issue with github api

### ISSUE THREAD

**Issue by cristiangiagante** [jenkinsci/ghprb-plugin#661]
I installed the plugin, I followed the tutorial from the plugin and setup all like it the tutorial sayd but I'm getting this error. Status are not being correctly updated with github.

I have the latest versions of all plugins and dependencies.

I want to get out this error. Thanks

```
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"target_url","message":"target_url must use http(s) scheme"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:690)
	at org.kohsuke.github.Requester._to(Requester.java:293)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1075)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:281)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:193)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:144)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:20)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1723)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 422, message: 'Unprocessable Entity' for URL: https://api.github.com/repos/Example/MyJob/statuses/76b48343f033121245e3ea859f04b96dd3ce8ee3
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	... 11 more
``` 

@bjoernhaeuser changed for readiability.

**Comment by bjoernhaeuser** [comment]
@ cristiangiagante the error message is quite clear, right? The message is `target_url must use http(s) scheme`. This essentially means that that status you are sending to GitHub is not a full URL.

Please provide your complete configuration or check if always set http/https in the configuration for jenkins.

**Comment by bjoernhaeuser** [comment]
FYI: I will close this issue if its stale in 7 to 14 days :)
