### ISSUE TITLE
[Github Pull request merger] is not failing the build when there is any merge conflict

### ISSUE THREAD

**Issue by saikirankv** [jenkinsci/ghprb-plugin#698]
In post build action I have selected `Github Pull request merger` and checked 
`Fail the build if the Pull Request can't be merged?`. The issue is when I have a PR with merge conflicts its showing error in console log but build is not failing. Here is the log...

```

Pull request cannot be automerged.
ERROR: FAILURE
Setting status of ec47f58b82ec93d27ddb5246fffffffff096b054 to SUCCESS with url https://xxx/ and message: 'Tests Passed
 '
No emails were triggered.
Finished: SUCCESS

```

**Comment by saikirankv** [comment]
@bjoernhaeuser  please look into it.
Thanks

**Comment by bjoernhaeuser** [comment]
@saikirankv could you please test if #703 solves the problem for you?

**Comment by saikirankv** [comment]
ok I'll test and let you know.

**Comment by bjoernhaeuser** [comment]
@saikirankv any news? :)

**Comment by saikirankv** [comment]
Hi @bjoernhaeuser 
    I have pulled your code into local and tried running hpi:run in the home folder, its failing with 
`osiINFO: Started initialization
tory/org/jenkins-ci/main/jenkins-war/2.7/jenkins-war-2.7.war}
[INFO] Restart completed at Fri Aug 24 12:29:09 IST 2018
Aug 24, 2018 12:29:09 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Aug 24, 2018 12:29:09 PM hudson.ExtensionFinder$Sezpoz scout
WARNING: Failed to scout com.cloudbees.plugins.credentials.CredentialsSelectHelper
java.lang.ExceptionInInitializerError
	at com.cloudbees.plugins.credentials.CredentialsSelectHelper.<clinit>(CredentialsSelectHelper.java:82)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:669)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:465)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: attempt to register a second PermissionGroup for com.cloudbees.plugins.credentials.CredentialsProvider
	at hudson.security.PermissionGroup.register(PermissionGroup.java:135)
	at hudson.security.PermissionGroup.<init>(PermissionGroup.java:59)
	at com.cloudbees.plugins.credentials.CredentialsProvider.<clinit>(CredentialsProvider.java:136)
	... 16 more

Aug 24, 2018 12:29:09 PM hudson.ExtensionFinder$Sezpoz scout
WARNING: Failed to scout com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl
java.lang.NoClassDefFoundError: com.cloudbees.plugins.credentials.CredentialsProvider
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:669)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:465)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Aug 24, 2018 12:29:09 PM hudson.ExtensionFinder$Sezpoz scout
WARNING: Failed to scout com.cloudbees.plugins.credentials.ViewCredentialsAction$RootActionImpl
java.lang.NoClassDefFoundError: Could not initialize class com.cloudbees.plugins.credentials.CredentialsProvider
	at com.cloudbees.plugins.credentials.ViewCredentialsAction.<clinit>(ViewCredentialsAction.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:669)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:465)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Aug 24, 2018 12:29:09 PM hudson.ExtensionFinder$Sezpoz scout
WARNING: Failed to scout com.cloudbees.plugins.credentials.UserCredentialsProvider
java.lang.NoClassDefFoundError: com.cloudbees.plugins.credentials.CredentialsProvider
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:669)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:465)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Aug 24, 2018 12:29:10 PM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
WARNING: Failed to load com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl
java.lang.NoClassDefFoundError: com.cloudbees.plugins.credentials.CredentialsProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:476)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:506)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:471)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Aug 24, 2018 12:29:10 PM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
WARNING: Failed to load com.cloudbees.plugins.credentials.UserCredentialsProvider
java.lang.NoClassDefFoundError: com.cloudbees.plugins.credentials.CredentialsProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:476)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:506)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:471)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1014)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:80)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

Do you have any idea on how to resolve this?

**Comment by bjoernhaeuser** [comment]
@saikirankv 
just try `mvn clean package -DskipTests` :)

**Comment by saikirankv** [comment]
I cannot test this.

**Comment by bjoernhaeuser** [comment]
I will close this because #703 is merged now. You can deploy current master for testing and see if this  is really resolved for you.
