### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 401 for URL: api/v3/rate_limit

### ISSUE THREAD

**Issue by arielelkin** [jenkinsci/ghprb-plugin#723]
Plugin version: `1.42.0`
Jenkins version: `2.128`

I have configured a Jenkins job according to [the instructions](https://github.com/jenkinsci/ghprb-plugin/blob/master/README.md#creating-a-job). I have scheduled the job to run every minute (Crontab line is `* * * * *`), but the builds never start. 

Here are the logs:

```
Nov 21, 2018 11:25:00 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
Error while accessing rate limit API
java.io.IOException: Server returned HTTP response code: 401 for URL: https://MY.GITHUB.ENTERPRISE.URL/api/v3/rate_limit
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://MY.GITHUB.ENTERPRISE.URL/api/v3/rate_limit
	at sun.reflect.GeneratedConstructorAccessor384.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:617)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://MY.GITHUB.ENTERPRISE.URL/api/v3/rate_limit
	at org.kohsuke.github.Requester.parse(Requester.java:638)
	at org.kohsuke.github.Requester.parse(Requester.java:599)
	at org.kohsuke.github.Requester._to(Requester.java:277)
Caused: org.kohsuke.github.HttpException: {"message":"Must authenticate to access this API.","documentation_url":"https://developer.github.com/enterprise/2.13/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:695)
	at org.kohsuke.github.Requester._to(Requester.java:298)
	at org.kohsuke.github.Requester.to(Requester.java:239)
	at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:317)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:100)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:133)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:371)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I have verified that the credentials are valid (if I trigger the job manually the repo is cloned properly, but the build fails)

Any thoughts?

**Comment by bjoernhaeuser** [comment]
Sorry for the late response, but this usually means that ghprb is not correctly configured to use your enterprise github. This probably requires to scope the jenkins credentials to your domain. 

Having no idea about github enterprise though makes debugging this kinda hard.

**Comment by billypchan** [comment]
I fixed this issue by creating a new Github PAT with scopes: repo/workflow/write:packages/ admin:org/write:discussion and replace with old token with less scopes. Maybe less scopes is needed.
