### ISSUE TITLE
Missing method error when trying to use cancelBuildsOnUpdate DSL

### ISSUE THREAD

**Issue by ch4rms** [jenkinsci/ghprb-plugin#724]
I have unit tests running against our DSL jobs and for the life of me I could not figure out why I was getting MissingMethodErrors. 

`Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.cancelBuildsOnUpdate() is applicable for argument types: (ReactNativeJobs$_buildAndTestWebPR_closure6$_closure75$_closure80$_closure81$_closure82) values: [ReactNativeJobs$_buildAndTestWebPR_closure6$_closure75$_closure80$_closure81$_closure82@69ec89f8]
	at javaposse.jobdsl.dsl.AbstractExtensibleContext.methodMissing(AbstractExtensibleContext.groovy:19)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)`

`cancelBuildsOnUpdate()` exists in master:
https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java#L58-L63

But not in the tagged releases for 1.41.0 or 1.42.0

https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.42.0/src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java

I have confirmed that the class file in the jar, in the hpi, on maven central does NOT have the new method. 

I think this is related: https://github.com/jenkinsci/ghprb-plugin/pull/709#issuecomment-435418460

So for some reason the changes on the jobdsl haven't made it.  The extension classes themselves have made it.

**Comment by danbim** [comment]
When fixing this, it would also be great if this could be added to the documentation (= code listing) on README.md. It's not too obvious how to use it without any documentation.
