### ISSUE TITLE
Webhook creation not working for private repo

### ISSUE THREAD

**Issue by alexandruluca** [jenkinsci/ghprb-plugin#730]
Hi

I have recently tried out ghprb. Works perfectly fine on one of my public repos.
However it fails if I do the same for a private one. It fails with the following

```
Could not retrieve GitHub repository named {organization}/{repoName} (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: https://api.github.com/repos/{organization}/{repoName}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
Caused: java.io.FileNotFoundException: https://api.github.com/repos/{organization}/{repoName}
	at sun.reflect.GeneratedConstructorAccessor1887.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:625)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
```

I do have an accesstoken configured

**Comment by louisrli** [comment]
I ran into this issue and subscribed to this, eventually resolving it. IIRC it turns out to be an auth configuration issue with a bad error msg.

can't remember exactly what i did but this is my config

![image](https://user-images.githubusercontent.com/1303401/104758718-cb077680-5756-11eb-8324-9c3c6bed3553.png)

I have api.github.com credentials, don't remember how I made them but I followed the manual somewhere

![image](https://user-images.githubusercontent.com/1303401/104758859-ed998f80-5756-11eb-8ec7-90efec814e5a.png)

**Comment by alexandruluca** [comment]
> Any resolution?

Try this. This always works for me for private repos

```
Create jenkins ssh dir
> mkdir -p /var/lib/jenkins/.ssh

Add id_rsa and id_rsa.pub to   /var/lib/jenkins/.ssh

> chmod 400 id_rsa.pub
> chmod 400 id_rsa

Login as jenkins

> sudo su -s /bin/bash jenkins

Execute ls command to check if access is ok
> git ls-remote -h git@github.com:your-organization/your-private-repo.git HEAD
```
Setting up github pull request builder

```
> Go to jenkins > credentials > create new credential > type “secret” > enter github access token
> Go to jenkins > system configuration
> Go to “GitHub Pull Request Builder” section
> Add shared secret
```

**Comment by kumarsingh1993** [comment]
I am also looking for resolution

**Comment by alexandruluca** [comment]
> I am also looking for resolution

Check answer I posted above
