### ISSUE TITLE
Failed to load org.jenkinsci.plugins.github.pullrequest.extra.GitHubPRLabelUnblockQueueCondition$DescriptorImpl

### ISSUE THREAD

**Issue by tzaeru** [jenkinsci/ghprb-plugin#779]
In Jenkins logs, there's errors related to GHPRB:

```
May 22, 2020 9:09:29 AM WARNING org.jvnet.hudson.annotation_indexer.Index$2$1 fetch

Failed to load org.jenkinsci.plugins.github.pullrequest.extra.GitHubPRLabelUnblockQueueCondition$DescriptorImpl
java.lang.ClassNotFoundException: org.jenkinsci.plugins.blockqueuedjob.condition.BlockQueueCondition$BlockQueueConditionDescriptor
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/blockqueuedjob/condition/BlockQueueCondition$BlockQueueConditionDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1155)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:715)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1377)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
```

Repeated quite a few times.

Unsure if it actually breaks anything though.

**Comment by jasminen** [comment]
+ 1

**Comment by poxu** [comment]
I had that issue and I was able to solve it by installing **block-queued-job** plugin. Apparently github-pullrequest plugin depends on it.
