### ISSUE TITLE
Command similar to "retest this please" to stop all running tests

### ISSUE THREAD

**Issue by TobKed** [jenkinsci/ghprb-plugin#786]
It would be nice to have option to stop running / abort queued builds for PR.
Sometimes I can figure out that my PR have mistakes and requires some time consuming changes and I would like to stop running/queued tests to free up worker resources.

Command similar to "retest this please" like "stop testing this please" would be a perfect solution.
WDYT?

**Comment by lrm25** [comment]
Another reason for something like this:  at a company I'm doing work for, there was a connection issue on the Jenkins side when reporting the build result back to github, and the build was stuck in "Pending" on the github side for a while, even though the build was complete.  Something to just kill a build and restart would be nice.

The error:
C:\Program Files (x86)\Jenkins\workspace\<redacted>\src\<redacted>>exit 0 
Setting status of 7d08531357de100bf78693e4ca7dbca081c9e09d to SUCCESS with url http://10.2.2.46:8008/job/<redacted>/2234/ and message: 'Build finished. '
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.GHIOException: api.github.com
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:64)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:364)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:327)
	at org.kohsuke.github.Requester.fetch(Requester.java:74)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1897)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:283)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:241)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:205)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:28)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at hudson.model.Run.execute(Run.java:1925)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Caused by: java.net.UnknownHostException: api.github.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.buildRequest(GitHubHttpUrlConnectionClient.java:156)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.setupConnection(GitHubHttpUrlConnectionClient.java:121)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:61)
	... 13 more
Email was triggered for: Always
Sending email for trigger: Always
Sending email to: <redacted>
Finished: SUCCESS

**Comment by wanpengfei-git** [comment]
> Something to just kill a build and restart would be nice.

any reply or solution about this problem？
