### ISSUE TITLE
v1.22: Commit status doesn't add a link to the build and is not set at the end

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [jenkinsci/ghprb-plugin#94]
I just updated to the latest version and noticed that now there is no link to the build in the commit status, all I get from GitHub (at least the web interface) is: "Waiting to hear about a468a45 — Build triggered. sha1 is merged.", but no link to see the details as before.

Also, after the building is done, the commit status is not set appropriately (at least when the build was successful, I haven't check yet with failed builds).

**Comment by DavidTanner** [comment]
Did the build ever start?  Once the status changes to "Build Started, sha1 is merged" you should get a link.

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, the build are starting and finishing. I get the comments posted by ghprb, the commit status is the one not being updated. I even have the option to only comment when setting the status fails, so it might be that updating the statuses is failing for some reason, because I always get the comments instead.

**Comment by DavidTanner** [comment]
Are there errors in the system logs?

**Comment by DavidTanner** [comment]
The error is that the context is an empty string.  I will fix it and release 1.22.1.  The context either has to have something in it, or be null.

**Comment by leandro-lucarella-sociomantic** [comment]
I have a logger configured to log org.jenkinsci.plugins.ghprb, this is what I see:

```
Jun 01, 2015 6:06:36 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Checking issue comment 'org.kohsuke.github.GHIssueComment@425883dd' for repo some/repo

Jun 01, 2015 6:06:36 PM FINER org.jenkinsci.plugins.ghprb.GhprbRepository

Comment on issue #679 from User:leandro-lucarella-sociomantic: test this please jenkins

Jun 01, 2015 6:06:36 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Retest phrase

Jun 01, 2015 6:06:36 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Retest accepted and user User:leandro-lucarella-sociomantic is whitelisted

Jun 01, 2015 6:06:36 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Running the build

Jun 01, 2015 6:06:36 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

PR is not null, checking if mergable

Jun 01, 2015 6:06:37 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Running build...

Jun 01, 2015 6:07:30 PM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure

Trying to send comment.
org.jenkinsci.plugins.ghprb.extensions.GhprbCommitStatusException: Build finished.
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:88)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:75)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:306)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)

```

**Comment by leandro-lucarella-sociomantic** [comment]
Another one without a traceback (I've been playing with different settings adding or removing the messages, so maybe this is what it changed).
```
Jun 01, 2015 6:30:03 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Got payload event: pull_request

Jun 01, 2015 6:30:03 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Checking PR #679 for some/proj

Jun 01, 2015 6:30:03 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest check

Pull request #679 was updated on some/proj at 6/1/15 6:29 PM by User:leandro-lucarella-sociomantic

Jun 01, 2015 6:30:04 PM FINE org.jenkinsci.plugins.ghprb.GhprbPullRequest

New commit. Sha: a468a450c8704fbfcb7cdab0e99df91212f248eb => 86d90203c53fb91b22ccd9e88b43a6f16cbfaf25

Jun 01, 2015 6:30:04 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Running the build

Jun 01, 2015 6:30:04 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

PR is not null, checking if mergable

Jun 01, 2015 6:30:04 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest

Running build...

Jun 01, 2015 6:30:37 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure

Could not update commit status of the Pull Request on GitHub.

Jun 01, 2015 6:30:37 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure

Could not update commit status of the Pull Request on GitHub.

Jun 01, 2015 6:30:37 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Got payload event: issue_comment

Jun 01, 2015 6:30:37 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Checking issue comment 'org.kohsuke.github.GHIssueComment@5cda8984' for repo some/proj

Jun 01, 2015 6:30:37 PM FINER org.jenkinsci.plugins.ghprb.GhprbRepository

Comment on issue #679 from User:github-admin-sociomantic: 
Refer to this link for build results (access rights to CI server needed): 
https://jenkins/job/core-team/job/proj-pr/1384/

Jun 01, 2015 6:31:32 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure

Could not update commit status of the Pull Request on GitHub.

Jun 01, 2015 6:31:33 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Got payload event: issue_comment

Jun 01, 2015 6:31:33 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex

Checking issue comment 'org.kohsuke.github.GHIssueComment@2e49882f' for repo some/proj

Jun 01, 2015 6:31:33 PM FINER org.jenkinsci.plugins.ghprb.GhprbRepository

Comment on issue #679 from User:github-admin-sociomantic: 
Refer to this link for build results (access rights to CI server needed): 
https://jenkins//job/core-team/job/proj-pr/1385/

```

**Comment by leandro-lucarella-sociomantic** [comment]
Also, I noticed that adding the action to change the context, doesn't really change the context in the commit status (not a big problem to me, I wasn't using that, I just played with it while trying to make this work :).

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, I just noticed you already found and fixed the issue (hopefully)! Thanks for the very quick response!

**Comment by DavidTanner** [comment]
If you set the context in the job then the commit status would be updated.  Changing the context in the main configuration just sets a default for each job to use.

**Comment by DavidTanner** [comment]
The new version has been released, but it will take a few hours for it to show up in the update center.

**Comment by leandro-lucarella-sociomantic** [comment]
I used a context and it still failed to set the commit status after the initial "Build triggered. sha1 is merged." status. The context was always set to "default" (it doesn't matter if I defined in the ghprb config or not). This is at least what I see if I query the commit status for the merge commit using the github API.

**Comment by leandro-lucarella-sociomantic** [comment]
For now I downgraded to v1.21.1, tomorrow I'll try to give the new version a shot, but briefly because I leave for vacations for a week, and I must leave a working pull request tester in jenkins :)

Anyway, thanks again for the quick answer!

**Comment by DavidTanner** [comment]
There should also be useable stacks in the logs in the next version.

**Comment by leandro-lucarella-sociomantic** [comment]
v1.21.1 seems to be working fine, thanks!
