### ISSUE TITLE
Not starting the trigger causes all triggers to fail.

### ISSUE THREAD

**Issue by DavidTanner** [jenkinsci/ghprb-plugin#95]
If GhprbTrigger.start() doesn't call super.start() then it causes a null pointer when Jenkins tries run the cron triggers.  In my case because there are some disabled projects start() is returning before calling the super method.  I could only reproduce the bug locally by creating a new job, letting it get set up, disabling it, then restarting jenkins.  

Jun 02, 2015 11:20:01 AM WARNING hudson.triggers.Trigger$Cron doRun
Cron thread throw an exception
java.lang.NullPointerException
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:263)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DavidTanner** [comment]
Fixed in v1.22.2
